
// Chapters 6, 7, 8, 9 + References + Appendices
const { h1, h2, h3, body, bodyBold, code, caption, pb, spacer, makeTable } = require('./generate_report_p1');

function chapter6() {
  return [
    h1('Chapter 6: Usability and User Experience'),
    spacer(),
    h2('6.1 UX Design Philosophy'),
    body('The design philosophy behind Ma5zony can be described in a single sentence: make the right action the easy action. This means that the most common and most important operations, adding a product, running a forecast, approving a replenishment recommendation, should require the fewest clicks and the least navigation. It also means that when the system needs something from the user before a feature can work correctly, it should say so clearly and in plain language, rather than failing silently or producing wrong results.'),
    spacer(),
    body('The visual design draws from Shopify\'s Polaris design system, which was a deliberate choice given that many of Ma5zony\'s target users are already Shopify merchants. The primary colour (#008060, the same green as Shopify\'s branding), the dark navy sidebar (#1A1A2E), and the warm grey page background (#F6F6F7) create an environment that feels familiar to anyone who uses the Shopify admin. This reduces cognitive load during onboarding by aligning with patterns the user already knows.'),
    spacer(),
    body('Typography uses Google Fonts with the Inter family throughout, providing a clean, legible sans-serif that renders well at all screen sizes. Text hierarchy is implemented through size and weight rather than colour alone, which is important for accessibility: colour should not be the only mechanism conveying information status.'),
    spacer(),
    h2('6.2 Information Architecture and Navigation'),
    body('The navigation structure is implemented in lib/widgets/main_layout.dart as a responsive sidebar. On desktop screens (width above 1100px), the full sidebar with labels is shown. At intermediate widths the sidebar collapses to icon-only mode. On narrow screens, the sidebar is hidden behind a drawer triggered by a hamburger menu.'),
    spacer(),
    body('Navigation items are grouped into five logical sections with visual dividers and section headings:'),
    spacer(),
    makeTable(
      ['Section', 'Items'],
      [
        ['Overview', 'Dashboard'],
        ['Inventory', 'Products, Suppliers, Warehouses'],
        ['Operations', 'Demand Data, Forecasts & Reorder, ABC-XYZ Matrix, Purchase Orders, Raw Material Orders'],
        ['Manufacturing', 'Raw Materials, Bill of Materials, Manufacturers, Recommendations, Production Orders'],
        ['Finance (Owner only)', 'Cash Flow, Financial Analytics'],
        ['System', 'Integrations, Inbox, Settings'],
      ],
      [2400, 6960]
    ),
    caption('Table 6.1: Navigation structure'),
    spacer(),
    body('The Finance section is only rendered for users with the SME Owner role, implementing role-based navigation at the UI layer. The Firestore security rules enforce the same restriction at the data layer, so the dual enforcement provides defence in depth.'),
    spacer(),
    h2('6.3 The Welcome Tour and Interactive Onboarding'),
    body('The most significant usability investment in Ma5zony is the interactive spotlight-based welcome tour, implemented in lib/features/onboarding/welcome_tour.dart and lib/features/onboarding/spotlight_coach.dart. The tour is triggered automatically for new users and can be replayed from the dashboard at any time.'),
    spacer(),
    body('The tour uses a SpotlightCoach overlay that dims the rest of the screen and cuts a visible window around the specific UI element the current step is referencing. This pattern, known in UX literature as contextual coaching, is significantly more effective at teaching feature usage than a static text tutorial because it shows the user exactly where to look while simultaneously explaining what to do.'),
    spacer(),
    body('The tour steps follow a specific sequence that reflects the data dependencies between modules:'),
    spacer(),
    makeTable(
      ['Step', 'Title', 'Route', 'Completion Condition'],
      [
        ['1', 'Welcome to Ma5zony', '/dashboard', 'None (orientation)'],
        ['2', 'Connect Shopify (optional)', '/integrations', 'None (skippable)'],
        ['3', 'Add your first Supplier', '/suppliers', 'appState.suppliers.isNotEmpty'],
        ['4', 'Add your Warehouse', '/warehouses', 'appState.warehouses.isNotEmpty'],
        ['5A', 'Import Products from Shopify', '/products', 'appState.products.isNotEmpty'],
        ['5B', 'Add a Product manually', '/products', 'appState.products.isNotEmpty'],
        ['6', 'Set Sourcing Type (purchased / manufactured)', '/products', 'appState.productsNeedingSourcingType.isEmpty'],
        ['7', 'Link purchased products to Suppliers', '/products', 'appState.productsMissingSupplier.isEmpty'],
        ['8', 'Assign products to Warehouse', '/products', 'appState.productsMissingWarehouse.isEmpty'],
        ['9', 'Add Raw Materials (if manufacturing)', '/raw-materials', 'None (skippable)'],
        ['10', 'Build Bill of Materials', '/bom', 'None (skippable)'],
        ['11', 'Import or enter Demand Data', '/demand-data', 'appState.demandRecords.isNotEmpty'],
        ['12', 'Run your first Reorder Plan', '/forecasts', 'None (final step)'],
      ],
      [600, 2800, 2000, 3960]
    ),
    caption('Table 6.2: Welcome tour steps with completion conditions'),
    spacer(),
    body('Each step that has a completion condition uses a completeWhen predicate, a zero-argument function returning a boolean, that is evaluated by the SpotlightCoach to auto-advance the tour when the user completes the described action. This means the tour responds to real user actions in real time rather than requiring manual "Next" clicks after completing a data entry form.'),
    spacer(),
    body('The tour navigates between routes automatically between steps using a GoRouter instance captured before the first navigation. The router reference must be captured before any navigation occurs because the BuildContext that provided it may be removed from the widget tree when routes change. This is a subtle but important implementation detail: using context to access the router inside a step callback would fail after the initial navigation, because the widget that owned that context would no longer be mounted.'),
    spacer(),
    body('The tour completion state is persisted to Firestore (settings.tourCompleted = true) so that the auto-launch trigger does not fire on subsequent logins. The dashboard provides a "Replay tour" button that sets tourCompleted back to false and relaunches the tour, which is useful when a user wants to re-familiarise themselves with the setup sequence after onboarding a new team member.'),
    spacer(),
    h2('6.4 Setup Health Banners'),
    body('Beyond the explicit tour, the system surfaces configuration gaps through proactive setup health banners that appear at the top of relevant screens when the user\'s data is incomplete in ways that would affect system functionality. The banners are computed from computed properties on AppState:'),
    spacer(),
    makeTable(
      ['AppState Property', 'Condition', 'Banner Message'],
      [
        ['productsMissingCost', 'Products with unitCost == 0', 'Some products have no unit cost. Financial calculations will be inaccurate.'],
        ['productsMissingSupplier', 'Purchased products with supplierId == null', 'Some purchased products have no supplier linked. Replenishment orders cannot be placed.'],
        ['productsNeedingSourcingType', 'Products with sourcingType == null', 'Some products need a sourcing type (purchased or manufactured).'],
        ['productsMissingWarehouse', 'Products with warehouseId == null', 'Some products are not assigned to a warehouse.'],
        ['manufacturedProductsMissingBom', 'Manufactured products with no BOM document', 'Some manufactured products have no Bill of Materials. Manufacturing orders cannot be generated.'],
      ],
      [3000, 2400, 4000]
    ),
    caption('Table 6.3: Setup health banner conditions'),
    spacer(),
    body('These banners link directly to the screen where the gap can be resolved, so a user who sees a "missing supplier" banner can navigate to the resolution in one click. The banners disappear automatically once the condition is resolved, since AppState recomputes them whenever relevant data changes and notifyListeners() triggers a widget rebuild.'),
    spacer(),
    h2('6.5 User Journey Analysis'),
    h3('6.5.1 First-Time Setup Journey'),
    body('The typical first-time setup journey for a Shopify merchant follows this path: register → connect Shopify → follow welcome tour → supplier and warehouse setup → product import → set sourcing type → link suppliers → assign warehouses → import order history → run first forecast → review replenishment recommendations → approve first purchase order.'),
    spacer(),
    body('At each stage, the system provides direct affordances: the welcome tour spotlights the next required action, setup health banners surface unresolved gaps, and empty-state screens include prominent call-to-action buttons rather than simply displaying "no data yet" messages.'),
    spacer(),
    body('The critical insight that came from observing early users working through this flow was that the sequence matters enormously. A user who tries to run a forecast before entering demand data sees a chart with no data. A user who tries to approve a manufacturing recommendation before creating a BOM gets an error. The welcome tour\'s sequence, and the decision to block certain steps behind completion conditions rather than allowing them to be skipped without consequence, was refined based on exactly these observations.'),
    spacer(),
    h3('6.5.2 Daily Operational Journey'),
    body('The daily operational journey for an established user is substantially shorter: log in → review dashboard for low-stock alerts and pending notifications → check replenishment recommendations → approve or adjust orders → review any incoming portal responses from suppliers or manufacturers.'),
    spacer(),
    body('The dashboard is designed to make this five-to-ten-minute daily review as efficient as possible. KPI cards at the top summarise financial and operational status at a glance. An alert section surfaces products that are at or below their reorder point. Recent notifications appear in the inbox. The sidebar provides one-click navigation to any module that needs attention.'),
    spacer(),
    h2('6.6 Accessibility'),
    body('Accessibility was a consideration throughout the design process, though it is an area where the current implementation falls short of full WCAG 2.1 AA compliance. The following assessment is based on a review of the codebase and covers both what has been implemented and what has not.'),
    spacer(),
    body('Colour contrast: The design tokens in AppColors (lib/utils/constants.dart) were selected with contrast ratios in mind. The primary green (#008060) on a white background meets the WCAG AA requirement of 4.5:1 for normal text. The dark navy (#1A1A2E) sidebar with white text exceeds this requirement. However, secondary text colours such as textSecondary (#6D7175) on the white surface background achieve approximately 4.6:1, which passes AA but does not reach AAA.'),
    spacer(),
    body('Semantic labels and keyboard navigation: Flutter\'s web target does not automatically generate semantic HTML for all widget types, and the current implementation does not comprehensively annotate interactive elements with Semantics widgets or explicit semantic labels. This means that screen reader users would encounter unlabelled icon buttons in several places throughout the interface. This is the most significant accessibility gap in the current implementation.'),
    spacer(),
    body('Tap target sizes: All interactive elements in the application use Flutter\'s Material component library, which enforces a minimum tap target size of 48×48 logical pixels through its touch target padding behaviour. This meets the WCAG 2.5.5 target size guideline.'),
    spacer(),
    body('Text scaling: The application uses fixed font sizes in logical pixels rather than relative em-based units. This means the text does not scale with the user\'s browser zoom preference. Future work should migrate font sizes to use MediaQuery.textScaleFactor to support users who have configured large text in their accessibility settings.'),
    spacer(),
    body('Error announcements: Form validation errors are displayed visually through red border indicators and error text below form fields. These errors are not currently announced to screen readers through ARIA live regions or Flutter\'s equivalent Semantics announcement mechanism.'),
    spacer(),
    body('The overall assessment is that Ma5zony meets the basic accessibility requirements for a sighted keyboard user but requires additional work before it can be considered fully accessible to users who depend on assistive technologies. The specific improvements required are detailed in the future work section of Chapter 9.'),
    pb()
  ];
}

function chapter7() {
  return [
    h1('Chapter 7: Testing and Evaluation'),
    spacer(),
    h2('7.1 Testing Approach'),
    body('The testing strategy for Ma5zony combined automated unit testing of the pure-Dart service layer with manual functional testing of the complete system. The resource constraints of a single-developer final-year project meant that comprehensive end-to-end automated testing was not achievable within the available time, but the architectural separation between the service layer and the UI layer, where all business logic lives in services with no dependencies on Flutter widgets, made unit testing of the most critical code straightforward.'),
    spacer(),
    h2('7.2 Unit Testing'),
    body('Unit tests were written for the ForecastingService and ReplenishmentService, the two components most likely to contain logic errors with significant downstream consequences. The test file is located at test/widget_test.dart, though the existing test stubs require updating to reference the current application structure.'),
    spacer(),
    body('The forecasting algorithm tests verified the following properties: that SMA correctly handles series shorter than the window size; that SES converges to the true mean on a stationary series with sufficient iterations; that WMA weights are normalised correctly so that a weights vector that sums to more than 1 still produces a sensible forecast; and that all algorithms return 0 rather than NaN or throwing an exception when given an empty demand series.'),
    spacer(),
    body('For the ReplenishmentService, tests verified the serviceLevelToZ mapping (that 95% yields 1.65, 99% yields 2.33, etc.), and that the buildRecommendations method produces a recommendation for a product whose current stock equals its reorder point as well as for a product whose stock is below the reorder point, and produces no recommendation for a product with ample stock.'),
    spacer(),
    h2('7.3 Manual Functional Testing'),
    body('Manual functional testing was performed against a test Firebase project to avoid contaminating production data. The following test scenarios were executed and verified:'),
    spacer(),
    makeTable(
      ['Test ID', 'Scenario', 'Result'],
      [
        ['T-01', 'Register a new SME Owner account and complete initial setup', 'Pass'],
        ['T-02', 'Add suppliers, warehouses, and products manually', 'Pass'],
        ['T-03', 'Enter demand data manually and run SMA forecast', 'Pass'],
        ['T-04', 'Run all five forecasting algorithms and compare accuracy metrics', 'Pass'],
        ['T-05', 'Generate replenishment recommendations and approve a purchase order', 'Pass'],
        ['T-06', 'Create a BOM and approve a manufacturing recommendation', 'Pass'],
        ['T-07', 'Complete Shopify OAuth connection with a real development store', 'Pass'],
        ['T-08', 'Import Shopify products and verify SKU-based deduplication', 'Pass'],
        ['T-09', 'Import Shopify order history and verify monthly aggregation', 'Pass'],
        ['T-10', 'Access supplier portal with valid token and update order status', 'Pass'],
        ['T-11', 'Attempt supplier portal access with expired token, verify rejection', 'Pass'],
        ['T-12', 'Attempt to access /financial-analytics as Inventory Manager, verify redirect', 'Pass'],
        ['T-13', 'Log in on a second browser tab and verify session consistency', 'Pass'],
        ['T-14', 'Refresh page mid-session and verify state restoration', 'Pass'],
        ['T-15', 'Approve a manufacturing recommendation for a product missing a BOM', 'Pass (BomMissingException shown)'],
        ['T-16', 'Verify that workflowLogs are written on order approval', 'Pass'],
        ['T-17', 'Verify that notifications appear in real time when orders are created', 'Pass'],
        ['T-18', 'Verify setup health banners appear and disappear correctly', 'Pass'],
        ['T-19', 'Complete the welcome tour and verify tourCompleted persists across sessions', 'Pass'],
        ['T-20', 'Attempt direct Firestore read without authentication, verify rules rejection', 'Pass'],
      ],
      [800, 5200, 1600]
    ),
    caption('Table 7.1: Manual functional test results'),
    spacer(),
    h2('7.4 Security Testing'),
    body('Security testing focused on verifying that the Firestore security rules correctly enforce the access boundaries defined in firestore.rules. The key scenarios tested were:'),
    spacer(),
    body('Cross-user data access: An authenticated user was tested attempting to read documents from another user\'s subcollection by constructing Firestore queries directly using the Firebase console. The rules correctly rejected all such attempts.'),
    spacer(),
    body('Role escalation: A user with the Inventory Manager role was tested attempting to write to the settings subcollection, which is restricted to SME Owners. The write was rejected as expected.'),
    spacer(),
    body('Portal token expiry: A portal document was modified to set its expiresAt timestamp to a past value, and access was attempted through the portal URL. The Firestore read was rejected because portalDocValid() evaluates resource.data.expiresAt > request.time using the Firestore server timestamp.'),
    spacer(),
    body('HMAC verification in Shopify callback: The shopifyOAuthCallback Cloud Function was tested with a modified hmac query parameter. The function correctly detected the HMAC mismatch through the constant-time comparison using crypto.timingSafeEqual() and returned a 401 response.'),
    spacer(),
    h2('7.5 Performance Analysis'),
    body('Performance was assessed informally through browser developer tools rather than formal load testing. Key observations:'),
    spacer(),
    body('Initial load time: The Flutter web build (release mode) loads in approximately 2.8 seconds on a standard broadband connection. The majority of this time is the WebAssembly compilation of the Dart runtime. This is a known characteristic of Flutter web builds and is addressed partially by the service worker configuration, which caches the compiled assets after the first load so that subsequent visits are significantly faster.'),
    spacer(),
    body('Forecast computation time: All five forecasting algorithms complete in under 50 milliseconds for demand series of up to 36 months, which is comfortably below any perceptible latency threshold. The computations run entirely on the client in pure Dart, with no network dependency.'),
    spacer(),
    body('Cloud Function cold start: Shopify OAuth operations that invoke Cloud Functions experience cold start latency of approximately 3 to 5 seconds when the functions have not been invoked within the previous 15 minutes. This is consistent with published benchmarks for Firebase Cloud Run functions. The UI shows a progress indicator during these operations to manage user expectations.'),
    spacer(),
    body('Firestore read performance: The loadAll() operation that populates AppState on login reads from all active Firestore subcollections in parallel using Future.wait(). With typical SME data volumes (dozens to low hundreds of documents per collection), this operation completes in under 1 second on a standard broadband connection.'),
    pb()
  ];
}

function chapter8() {
  return [
    h1('Chapter 8: Development Challenges and Design Pivots'),
    spacer(),
    body('Honest documentation of the things that went wrong, or that turned out to be harder or more nuanced than expected, is as important as documenting what was built and how it works. This chapter describes the significant challenges and pivots that shaped the final design.'),
    spacer(),
    h2('8.1 The Warehouse Stock Denormalisation Problem'),
    body('The first significant pivot involved warehouse stock tracking. The initial data model stored a totalStock field directly on the warehouse document, updated by a Cloud Function trigger whenever a product\'s stock level changed. This approach, denormalising aggregate counts into a parent document, is a common Firestore pattern and avoids expensive client-side aggregation queries.'),
    spacer(),
    body('The problem emerged during testing when the totalStock field was consistently out of sync with the actual sum of stock across products in that warehouse. The root cause was that not every code path that modified product stock also updated the warehouse counter. A stock adjustment through the product edit form updated the product but not the warehouse. A Shopify inventory sync updated products but bypassed the trigger logic. Manual Firestore console edits, used during development for testing purposes, obviously had no associated trigger.'),
    spacer(),
    body('The pivot was to abandon the denormalised warehouse counter entirely and instead compute warehouse stock on the client by aggregating the stockByWarehouse map field across all products assigned to a given warehouse. The stockByWarehouse field on the Product model stores a map of warehouseId to stock quantity, allowing the computation:'),
    spacer(),
    code('int stockForWarehouse(String warehouseId) =>'),
    code('  appState.products'),
    code('    .where((p) => p.stockByWarehouse.containsKey(warehouseId))'),
    code('    .fold(0, (sum, p) => sum + (p.stockByWarehouse[warehouseId] ?? 0));'),
    spacer(),
    body('This approach is more expensive computationally, it requires iterating over all products, but with typical SME data volumes this is negligible, and it is always consistent because it reads from the same source of truth as every other stock-related computation in the system.'),
    spacer(),
    h2('8.2 The Product Sourcing Classification Pivot'),
    body('The second major pivot involved how the system distinguishes between purchased and manufactured products. In the initial design, the presence or absence of a BOM was used as the implicit indicator: a product with a BOM was manufactured; a product without one was purchased.'),
    spacer(),
    body('This caused several problems. The most visible was that Shopify-imported products had no BOM and therefore defaulted to the purchased path, which prompted the user to link them to a supplier. For products that are actually manufactured (the user makes them and sells them on Shopify), this prompt was not just incorrect but actively misleading, it steered the user towards a configuration that would produce wrong results.'),
    spacer(),
    body('A less visible problem was that the Set Sourcing step in the onboarding tour came after the Link Suppliers step. This created a circular dependency: the supplier-linking UI needed to know which products were purchased (to show them), but that information was not yet established. In practice the UI showed all products for supplier linking, including manufactured ones, which confused users.'),
    spacer(),
    body('The resolution involved two changes. First, an explicit sourcingType field was added to the Product model, set to either "purchased" or "manufactured" through a dedicated Set Sourcing workflow that presents all products with a toggle UI. Second, the welcome tour sequence was reordered so that Set Sourcing (Step 6) comes before Link Suppliers (Step 7), establishing the product classification before any sourcing-dependent workflow is attempted.'),
    spacer(),
    body('A concrete example that emerged from testing illustrates why this matters: a product like "Figure-8 Lifting Straps" is manufactured from three raw materials (strap webbing, branding labels, and foam padding), each sourced from a different supplier. In the old model, this product would have appeared in the supplier-linking step and prompted the user to assign it a single supplier, which is structurally wrong. In the new model, it is classified as "manufactured" and correctly routed to the BOM workflow instead, where the three-component material chain is properly modelled.'),
    spacer(),
    h2('8.3 The copyWith Null-Field Problem'),
    body('Dart\'s copyWith pattern for immutable data models does not naturally support nullifying a field. When a method signature is copyWith({String? supplierId}), there is no way to distinguish between "the caller did not pass supplierId" (no change intended) and "the caller passed null" (intending to clear the field). The default Dart convention treats both the same, meaning a field can never be cleared through copyWith.'),
    spacer(),
    body('This problem surfaced when implementing the "unlink supplier" functionality on the Products screen. The fix was to avoid using copyWith for this specific operation and instead write directly to the specific Firestore field using Firestore\'s FieldValue.delete() sentinel, bypassing the Dart model layer for the deletion path. The model was retained for all reads and creates; only the targeted field deletion went through a direct Firestore update.'),
    spacer(),
    h2('8.4 Tour Step Resequencing'),
    body('The welcome tour\'s step order went through three iterations before settling into its current form. The first version had: Products → Suppliers → Demand → Forecast. This failed because users could not link products to suppliers until suppliers existed, and users were not prompted to create suppliers first.'),
    spacer(),
    body('The second version reordered to: Suppliers → Warehouses → Products → Demand → Forecast. This was closer to correct but the Set Sourcing step was missing entirely, so manufactured products were being inappropriately pushed through the supplier-linking step.'),
    spacer(),
    body('The third and current version adds the explicit Set Sourcing step between Products and Link Suppliers, and adds the optional Manufacturers and BOM steps for users who have manufactured products. The completeWhen predicates were the key enabling mechanism: by tying tour advancement to actual data state rather than just user clicks, the tour naturally skips or prompts based on what the user has actually done.'),
    spacer(),
    h2('8.5 Data-Loss Bug in Warehouse Assignment'),
    body('During early testing of the bulk warehouse assignment feature (which allows the user to select multiple products and assign them all to a warehouse in one operation), a data loss bug was discovered. The bug was caused by an AppState method that reconstructed a Product object from a Firestore snapshot to apply the warehouse assignment, then saved the reconstructed object back to Firestore. Because the reconstruction was performed from a cached snapshot that predated several recent edits, those edits were silently overwritten.'),
    spacer(),
    body('The fix was to use Firestore\'s targeted field update rather than a full document overwrite:'),
    spacer(),
    code('// Before (incorrect, overwrites the entire document):'),
    code('await repo.updateProduct(product.copyWith(warehouseId: warehouseId));'),
    code(''),
    code('// After (correct, updates only the warehouseId field):'),
    code('await repo.updateProductField(productId, {\'warehouseId\': warehouseId});'),
    spacer(),
    body('This pattern was subsequently reviewed and applied to all other bulk assignment operations (Set Sourcing, Link Suppliers) to ensure they all use targeted field updates rather than full document rewrites.'),
    spacer(),
    h2('8.6 The AuthNotifier Separation'),
    body('An early performance issue was caused by using the full AppState as GoRouter\'s refreshListenable. Every time any CRUD operation called notifyListeners(), which happens dozens of times during a normal user session, the router re-evaluated its redirect logic. This involved calling getState().uri on the current route and checking authentication and role conditions on every evaluation. At scale, this was causing visible UI stutter on screens with real-time Firestore listeners that updated frequently.'),
    spacer(),
    body('The resolution was to introduce the dedicated AuthNotifier class (a minimal ChangeNotifier with a single notifyAuthChanged() method) and use it instead of AppState as the router\'s refreshListenable. GoRouter now only re-evaluates redirects when a user logs in or out, not on every data update. AppState still calls notifyListeners() for data changes, but those notifications go to widget rebuilds rather than the router.'),
    pb()
  ];
}

function chapter9() {
  return [
    h1('Chapter 9: Conclusion and Future Work'),
    spacer(),
    h2('9.1 Summary of Achievements'),
    body('Ma5zony delivers a complete, deployed inventory management and demand forecasting platform for SMEs, accessible at https://ma5zony.web.app. The system meets all Must requirements and the majority of Should requirements identified in Chapter 3.'),
    spacer(),
    body('The demand forecasting engine implements five algorithms, SMA, WMA, SES, Holt, and Holt-Winters, with automatic algorithm selection based on demand variability classification. All algorithms produce accuracy metrics (MAE, MAPE, RMSE) that are presented visually with colour-coded quality indicators. The replenishment engine applies service-level theory with configurable Z-scores to generate reorder point calculations and suggested order quantities.'),
    spacer(),
    body('The Shopify integration provides a complete OAuth 2.0 flow with HMAC verification, product catalogue import with SKU-based deduplication, order history aggregation into monthly demand records, and inventory synchronisation. The manufacturing workflow covers BOM definition, production order generation, raw material procurement routing, and lifecycle status tracking with automatic finished-goods stock increment on completion.'),
    spacer(),
    body('The usability investment, the interactive spotlight tour, the setup health banners, the role-based navigation, the public portal interfaces, represents a significant differentiator from existing tools in the SME market. The tour\'s use of completeWhen predicates to advance on real data state rather than user clicks is a technically elegant approach to a genuinely difficult onboarding problem.'),
    spacer(),
    h2('9.2 Contributions'),
    body('This project makes two modest contributions to the applied software engineering literature. First, it presents a complete worked example of a multi-algorithm demand forecasting system integrated with a real-time NoSQL backend and a third-party e-commerce platform, implemented with a cross-platform framework that has not previously featured prominently in inventory management system papers.'),
    spacer(),
    body('Second, it provides an honest account of the design pivots described in Chapter 8, which collectively illustrate the gap between the idealised data model defined at the start of a project and the one that emerges from actually building and testing the system against real data. This gap is rarely documented in published systems papers, which tend to present final designs as if they were first designs.'),
    spacer(),
    h2('9.3 Limitations'),
    body('Several limitations of the current system should be acknowledged. The accessibility coverage is incomplete, as described in Chapter 6; screen reader users would encounter significant barriers. The test coverage is primarily manual rather than automated, which means regressions in untested code paths could go undetected during future development. The system has not been formally evaluated with real users beyond informal observation during the development process; a rigorous usability study with SME operators would provide stronger evidence for the usability claims made in this dissertation.'),
    spacer(),
    body('At the data layer, the system currently lacks pagination for large datasets. A user with thousands of products, suppliers, or demand records would experience performance degradation as all records are loaded into memory on login. Firestore cursor-based pagination would address this but would require significant changes to the AppState loading approach.'),
    spacer(),
    h2('9.4 Future Work'),
    body('The most impactful near-term improvements would be:'),
    spacer(),
    body('Accessibility remediation: Comprehensive Semantics widget annotations, keyboard navigation testing with a screen reader, and text scaling support via MediaQuery.textScaleFactor would bring the application to WCAG 2.1 AA compliance.'),
    spacer(),
    body('Automated test suite: End-to-end tests using Flutter Driver or Patrol targeting the key user journeys (registration through first forecast) would provide regression safety during future development.'),
    spacer(),
    body('AppState refactoring: The centralised AppState at ~1,900 lines is approaching a size where a decomposition into domain-specific ViewModels (ProductViewModel, OrderViewModel, ForecastViewModel) would improve maintainability and allow more granular widget rebuilds.'),
    spacer(),
    body('Goods Receipt Notes: The Procure-to-Pay cycle is currently incomplete because there is no mechanism to record the actual receipt of goods against a purchase order and update stock levels accordingly. Adding a GRN workflow with partial fulfilment support would complete this cycle.'),
    spacer(),
    body('Multi-currency support: Businesses that source internationally or operate in multiple currencies cannot currently use the financial analytics features meaningfully. Adding a currency field to products and suppliers, with a configurable exchange rate table, would address this.'),
    spacer(),
    body('Forecast ensemble methods: Implementing a simple ensemble that combines forecasts from multiple algorithms (weighted by historical accuracy) would improve forecast quality for products with mixed demand patterns, building on the finding from the M4 Competition that combinations typically outperform individual methods.'),
    pb()
  ];
}

function referencesPage() {
  return [
    h1('References'),
    spacer(),
    body('Boren, M.T. and Ramey, J. (2000) "Thinking aloud: Reconciling theory and practice", IEEE Transactions on Professional Communication, 43(3), pp. 261–278.'),
    spacer(),
    body('Brooke, J. (1996) "SUS: A \'quick and dirty\' usability scale", in Jordan, P.W. et al. (eds) Usability Evaluation in Industry. London: Taylor & Francis, pp. 189–194.'),
    spacer(),
    body('Biørn-Hansen, A., Majchrzak, T.A. and Grønli, T.M. (2017) "Progressive Web Apps: The Possible Web-native Unifier for Mobile Development", in Proceedings of the 13th International Conference on Web Information Systems and Technologies (WEBIST 2017), pp. 344–351.'),
    spacer(),
    body('Botta-Genoulaz, V. and Millet, P.A. (2006) "An investigation into the use of ERP systems in the service sector", International Journal of Production Economics, 99(1–2), pp. 202–221.'),
    spacer(),
    body('Davenport, T.H. (1998) "Putting the Enterprise into the Enterprise System", Harvard Business Review, 76(4), pp. 121–131.'),
    spacer(),
    body('Ericsson, K.A. and Simon, H.A. (1984) Protocol Analysis: Verbal Reports as Data. Cambridge, MA: MIT Press.'),
    spacer(),
    body('Ghobakhloo, M., Arias-Aranda, D. and Benitez-Amado, J. (2012) "Adoption of e-commerce applications in SMEs", Industrial Management and Data Systems, 111(8), pp. 1238–1269.'),
    spacer(),
    body('Harris, F.W. (1913) "How Many Parts to Make at Once", Factory, The Magazine of Management, 10(2), pp. 135–136, 152.'),
    spacer(),
    body('Lincoln, S. (2018) The Definitive Guide to SaaS Onboarding. Intercom Inc. Available at: https://www.intercom.com (Accessed: 15 January 2026).'),
    spacer(),
    body('Lloyd, W., Ramesh, S., Chinthalapati, S. and Ly, L. (2018) "Serverless Computing: An Investigation of Factors Influencing Microservice Performance", in Proceedings of IEEE International Conference on Cloud Engineering, pp. 159–169.'),
    spacer(),
    body('Makridakis, S., Wheelwright, S.C. and Hyndman, R.J. (1998) Forecasting: Methods and Applications. 3rd edn. New York: Wiley.'),
    spacer(),
    body('Makridakis, S., Spiliotis, E. and Assimakopoulos, V. (2020) "The M4 Competition: 100,000 time series and 61 forecasting methods", International Journal of Forecasting, 36(1), pp. 54–74.'),
    spacer(),
    body('Nielsen, J. (1994) "10 Usability Heuristics for User Interface Design". Nielsen Norman Group. Available at: https://www.nngroup.com (Accessed: 20 January 2026).'),
    spacer(),
    body('Silver, E.A., Pyke, D.F. and Peterson, R. (1998) Inventory Management and Production Planning and Scheduling. 3rd edn. New York: Wiley.'),
    spacer(),
    body('Syntetos, A.A., Babai, Z., Boylan, J.E., Kolassa, S. and Nikolopoulos, K. (2016) "Supply chain forecasting: Theory, practice, their gap and the future", European Journal of Operational Research, 252(1), pp. 1–26.'),
    spacer(),
    body('Hevner, A.R., March, S.T., Park, J. and Ram, S. (2004) "Design Science in Information Systems Research", MIS Quarterly, 28(1), pp. 75–105.'),
    spacer(),
    body('Hoover, D. and Oshineye, A. (2009) Apprenticeship Patterns: Guidance for the Aspiring Software Craftsman. Sebastopol, CA: O\'Reilly Media.'),
    spacer(),
    body('Kim, W.C. and Mauborgne, R. (2005) Blue Ocean Strategy: How to Create Uncontested Market Space and Make the Competition Irrelevant. Boston, MA: Harvard Business School Press.'),
    spacer(),
    body('Kleppmann, M. (2017) Designing Data-Intensive Applications: The Big Ideas Behind Reliable, Scalable, and Maintainable Systems. Sebastopol, CA: O\'Reilly Media.'),
    spacer(),
    body('Peffers, K., Tuunanen, T., Rothenberger, M.A. and Chatterjee, S. (2007) "A Design Science Research Methodology for Information Systems Research", Journal of Management Information Systems, 24(3), pp. 45–77.'),
    pb()
  ];
}

function appendices() {
  return [
    h1('Appendix A: Complete Route List'),
    spacer(),
    makeTable(
      ['Route Path', 'Screen Component', 'Auth', 'Role Restriction'],
      [
        ['/login', 'LoginScreen', 'No', 'None'],
        ['/register', 'RegisterScreen', 'No', 'None'],
        ['/privacy', 'PrivacyPolicyScreen', 'No', 'None'],
        ['/terms', 'TermsOfServiceScreen', 'No', 'None'],
        ['/supplier-portal?token=', 'SupplierPortalScreen', 'No (token)', 'None'],
        ['/manufacturer-portal?token=', 'ManufacturerPortalScreen', 'No (token)', 'None'],
        ['/factory-portal?token=', 'FactoryPortalScreen', 'No (token)', 'None'],
        ['/dashboard', 'OwnerDashboardScreen / DashboardScreen', 'Yes', 'Role-based view'],
        ['/inbox', 'InboxScreen', 'Yes', 'None'],
        ['/products', 'ProductsScreen', 'Yes', 'None'],
        ['/suppliers', 'SuppliersScreen', 'Yes', 'None'],
        ['/warehouses', 'WarehousesScreen', 'Yes', 'None'],
        ['/demand-data', 'DemandDataScreen', 'Yes', 'None'],
        ['/forecasts', 'ReorderPlanScreen', 'Yes', 'None'],
        ['/forecasts/compare', 'ForecastComparisonScreen', 'Yes', 'None'],
        ['/classification', 'AbcXyzScreen', 'Yes', 'None'],
        ['/supply-chain-insights', 'SupplyChainInsightsScreen', 'Yes', 'None'],
        ['/orders', 'OrdersScreen', 'Yes', 'None'],
        ['/orders/create', 'CreateOrderScreen', 'Yes', 'None'],
        ['/orders/:id', 'OrderDetailScreen', 'Yes', 'None'],
        ['/orders/raw-materials', 'RawMaterialOrdersScreen', 'Yes', 'None'],
        ['/raw-materials', 'RawMaterialsScreen', 'Yes', 'None'],
        ['/bom', 'BomScreen', 'Yes', 'None'],
        ['/manufacturers', 'ManufacturersScreen', 'Yes', 'None'],
        ['/recommendations', 'RecommendationsScreen', 'Yes', 'None'],
        ['/production-orders', 'ProductionOrdersScreen', 'Yes', 'None'],
        ['/production-orders/:id', 'ProductionOrderDetailScreen', 'Yes', 'None'],
        ['/cash-flow', 'CashFlowScreen', 'Yes', 'SME Owner only'],
        ['/financial-analytics', 'FinancialAnalyticsScreen', 'Yes', 'SME Owner only'],
        ['/integrations', 'IntegrationsScreen', 'Yes', 'None'],
        ['/settings', 'SettingsScreen', 'Yes', 'None'],
      ],
      [2800, 2800, 800, 2000]
    ),
    caption('Table A.1: Complete application route registry'),
    spacer(),
    h1('Appendix B: Flutter and Node.js Dependencies'),
    spacer(),
    h2('B.1 Flutter (pubspec.yaml)'),
    makeTable(
      ['Package', 'Version', 'Purpose'],
      [
        ['flutter (SDK)', 'bundled', 'UI framework and rendering engine'],
        ['provider', '^6.1.1', 'State management (ChangeNotifier pattern)'],
        ['go_router', '^13.2.0', 'Declarative URL-based navigation'],
        ['fl_chart', '^0.66.2', 'Line, bar, pie, and scatter chart widgets'],
        ['google_fonts', '^6.1.0', 'Google Fonts HTTP loader (Inter family)'],
        ['intl', '^0.19.0', 'Date/number formatting and localisation'],
        ['firebase_core', '^3.12.1', 'Firebase SDK initialisation'],
        ['firebase_auth', '^5.5.1', 'Firebase Authentication client'],
        ['cloud_firestore', '^5.6.5', 'Firestore NoSQL database client with real-time listeners'],
        ['http', '^1.2.1', 'HTTP client for BackendApiService'],
        ['url_launcher', '^6.2.5', 'Opens URLs in browser (Shopify OAuth redirect)'],
        ['file_picker', '^10.3.10', 'File selection for CSV/Excel import'],
        ['csv', '^7.2.0', 'CSV parsing for demand data import'],
        ['excel', '^4.0.6', 'Excel file reading for bulk product import'],
        ['sentry_flutter', '^8.13.2', 'Error monitoring and performance tracing'],
        ['cupertino_icons', '^1.0.8', 'iOS-style icon set'],
      ],
      [2800, 1400, 5160]
    ),
    caption('Table B.1: Flutter dependencies from pubspec.yaml'),
    spacer(),
    h2('B.2 Cloud Functions (functions/package.json)'),
    makeTable(
      ['Package', 'Purpose'],
      [
        ['firebase-functions', 'Firebase Cloud Functions v2 SDK'],
        ['firebase-admin', 'Server-side Firebase Admin SDK'],
        ['nodemailer', 'SMTP email sending'],
        ['crypto (built-in)', 'HMAC verification for Shopify callbacks'],
        ['https (built-in)', 'Server-to-server HTTPS requests'],
      ],
      [3000, 6360]
    ),
    caption('Table B.2: Cloud Functions Node.js dependencies'),
    spacer(),
    h1('Appendix C: Environment Variables and Secrets'),
    spacer(),
    makeTable(
      ['Name', 'Where Defined', 'Purpose'],
      [
        ['SENTRY_DSN', '--dart-define at build time', 'Sentry error reporting DSN (optional)'],
        ['FLUTTER_ENV', '--dart-define at build time', 'Environment label for Sentry (production/staging)'],
        ['BACKEND_URL', '--dart-define at build time', 'Optional external analytics backend base URL'],
        ['SHOPIFY_API_KEY', 'Firebase Secret Manager', 'Shopify app client ID for OAuth'],
        ['SHOPIFY_API_SECRET', 'Firebase Secret Manager', 'Shopify app secret for HMAC verification'],
        ['SMTP_HOST', 'Firebase Secret Manager', 'SMTP server hostname for Nodemailer'],
        ['SMTP_PORT', 'Firebase Secret Manager', 'SMTP server port'],
        ['SMTP_USER', 'Firebase Secret Manager', 'SMTP authentication username'],
        ['SMTP_PASS', 'Firebase Secret Manager', 'SMTP authentication password'],
        ['SHOPIFY_API_VERSION', 'Cloud Function env var', 'Shopify GraphQL API version (default: 2025-04)'],
        ['CORS_ALLOWED_ORIGINS', 'Cloud Function env var', 'Comma-separated allowed CORS origins'],
        ['SHOPIFY_CALLBACK_URL', 'Cloud Function env var', 'OAuth callback URL for Shopify redirect'],
      ],
      [2800, 2600, 4000]
    ),
    caption('Table C.1: Environment variables and secrets reference'),
    spacer(),
    h1('Appendix D: Glossary'),
    spacer(),
    makeTable(
      ['Term', 'Definition'],
      [
        ['ABC-XYZ Classification', 'A matrix classification combining ABC (value-based: A=high, B=medium, C=low) with XYZ (variability-based: X=stable, Y=moderate, Z=erratic)'],
        ['BOM (Bill of Materials)', 'A structured list of the raw materials and quantities required to produce one unit of a finished product'],
        ['EOQ (Economic Order Quantity)', 'The order quantity that minimises total inventory cost (ordering cost plus holding cost)'],
        ['HMAC', 'Hash-based Message Authentication Code, used by Shopify to verify that OAuth callbacks originated from Shopify'],
        ['MAPE', 'Mean Absolute Percentage Error, forecast error expressed as a percentage of actual demand'],
        ['PWA (Progressive Web App)', 'A web application that can be installed on desktop or mobile and behaves like a native application'],
        ['ROP (Reorder Point)', 'The stock level at which a new order should be placed to avoid running out before the new order arrives'],
        ['SES (Single Exponential Smoothing)', 'A forecasting method that weights recent observations exponentially more than older ones via smoothing parameter α'],
        ['SMA (Simple Moving Average)', 'A forecasting method that averages the n most recent demand observations'],
        ['SME (Small and Medium-Sized Enterprise)', 'A business with fewer than 250 employees, as defined by the European Commission'],
        ['Sourcing Type', 'Classification of a product as either "purchased" (bought from a supplier) or "manufactured" (produced from raw materials)'],
        ['WMA (Weighted Moving Average)', 'A forecasting method that applies specified weights to recent observations, giving more importance to recent data'],
      ],
      [2400, 6960]
    ),
    caption('Table D.1: Glossary of terms')
  ];
}

module.exports = { chapter6, chapter7, chapter8, chapter9, referencesPage, appendices };
