
// Extended content: methodology, evaluation, security, business analysis, future work
const { h1, h2, h3, body, bodyBold, code, caption, pb, spacer, makeTable } = require('./generate_report_p1');

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 1: Extended Research Methodology
// ─────────────────────────────────────────────────────────────────────────────
function extendedMethodology() {
  return [
    h1('Chapter 2 (Extended): Research Methodology'),
    spacer(),
    h2('2.5 Research Philosophy and Paradigm'),
    body('Every software project rests on assumptions about what counts as valid knowledge and how to get it. Making those assumptions explicit is not a formality, it forces honest choices about method and honest acknowledgement of what each method can and cannot establish. This dissertation is grounded in a pragmatic philosophy: a method is valuable if it produces practically useful insight, and quantitative and qualitative approaches should be mixed wherever doing so gives a clearer picture.'),
    spacer(),
    body('The stance on requirements is constructivist. The system\'s requirements were not sitting out there waiting to be discovered; they were worked out through conversation with potential users, observation of existing workflows, and repeated negotiation. Each interview surfaced terminology that differed from the formal vocabulary of inventory management, and each round of observation revealed assumptions that had to be revised. Domain knowledge in applied computing is built up through practice, not derived from first principles.'),
    spacer(),
    body('That said, empirical measurement was used wherever it was possible. Response times, error rates, Firestore read costs, these were recorded and used to justify design decisions. The pragmatic position is not anti-quantitative; it just refuses to treat quantification as automatically more rigorous than careful observation.'),
    spacer(),
    h2('2.6 Design Science Research'),
    body('The primary methodological framework is Design Science Research (DSR), formalised by Hevner et al. (2004) and elaborated by Peffers et al. (2007). DSR treats the construction of novel artefacts, software systems, models, frameworks, as a legitimate scholarly contribution, provided the construction is rigorous and the artefact\'s utility is evaluated against defined criteria.'),
    spacer(),
    body('Hevner\'s framework has three cycles: the relevance cycle connecting the research to a real-world problem, the design cycle of iterative construction and evaluation, and the rigour cycle ensuring the work draws on and contributes back to the discipline\'s knowledge base. Each is identifiable in the development of Ma5zony, though they did not happen in neat sequence, the design cycle kept pulling new relevance questions to the surface.'),
    spacer(),
    body('The relevance cycle started before a single line of code was written. The developer spent four weeks documenting inventory practices at three small businesses in the textile, electronics, and food distribution sectors. The pattern across all three was the same: decisions were made using gut feeling, Excel, and WhatsApp messages to suppliers. No business used any form of demand forecasting. They ordered more stock when something was running low and hoped their seasonal intuition was roughly right. This established the core problem clearly: these businesses needed a tool that could turn their transactional data into actionable reorder decisions without requiring them to understand statistics.'),
    spacer(),
    body('The design cycle ran through six iterations. The first evaluated a paper prototype of the dashboard and product list with two potential users. Their feedback was immediate and practical: the card layout was hard to scan, and they wanted to see days-of-stock prominently rather than buried in a detail view. That single insight drove the days-of-stock calculation and its placement in the product card subtitle.'),
    spacer(),
    body('The second iteration introduced the forecasting module. The initial version showed just a number, the forecasted demand for the next period, with no explanation. Users did not trust it. They had no way to judge whether the number was reasonable. This led to a redesign that shows the historical data points behind the forecast, a visual trend line, and a plain-language description of the algorithm. The lesson was that transparency in algorithmic output is not decoration: it is the difference between a feature users rely on and one they ignore.'),
    spacer(),
    body('Iterations three through six added the manufacturing workflow, Shopify integration, portal system, and financial analytics. Each followed the same loop: implement, deploy to the production Firebase project, use it as if running a real business for one to two weeks, identify what was missing or friction-heavy, and revise. This practice of dogfooding, the developer using their own product as a proxy for the target user, was effective partly because of direct familiarity with small retail operations and partly because it forced engagement with the system in conditions that replicated real use, not just task-completion in a testing session.'),
    spacer(),
    body('The rigour cycle runs through the dissertation as the thread connecting design decisions to established theory. The forecasting algorithm choices draw on Syntetos et al. (2016) and Makridakis et al. (1998). The usability evaluation uses Nielsen\'s ten heuristics (1994). The Firestore data modelling decisions follow Kleppmann\'s (2017) analysis of document database trade-offs. These connections are not retrofitted justifications, they shaped the decisions at the time they were made.'),
    spacer(),
    h2('2.7 Data Collection Methods'),
    body('Nine semi-structured interviews were conducted across the project, each running between 30 and 75 minutes. Sessions opened with a broad question, "walk me through how you manage your inventory today", before moving to scenario-based questions about specific situations: what happens when a supplier warns about a three-week delay, or when a product starts selling faster than expected. The semi-structured format meant unexpected topics could be followed without losing coverage of the core questions.'),
    spacer(),
    body('On two occasions, the developer observed inventory management activities directly at a small electronics retailer for half a day: receiving a delivery, updating stock records in Excel, fielding a customer availability query, placing a replenishment order by phone. The observation sessions surfaced things that interviews did not, the physical effort of counting stock, the frustration of searching across multiple Excel files for a supplier\'s phone number, and the time it took to manually calculate a reorder quantity. Those small frictions became explicit design targets.'),
    spacer(),
    body('Three interview participants also shared their Excel files and WhatsApp message histories, with consent. Reading through those documents was revealing. The data they actually tracked was much simpler than anticipated, just quantities in and quantities out, sometimes with a column for supplier names. The terminology they used bore little resemblance to formal inventory management vocabulary. And the decision-making was almost entirely reactive: something ran low, so they ordered more. The document analysis shaped both the data model and the language used in the Ma5zony interface.'),
    spacer(),
    h2('2.8 Evaluation Strategy'),
    body('Functional correctness was verified through unit testing of the forecasting and replenishment service classes, checking that mathematical outputs matched manually computed expected values. Usability was assessed through think-aloud sessions with five participants who completed predefined tasks in the live system. Performance was measured using Chrome DevTools with CPU and network throttling, targeting conditions that approximate mid-range hardware on a mobile connection.'),
    spacer(),
    body('These evaluation approaches map directly to the three quality concerns from the requirements: does the system compute correct results, can users operate it without help, and does it perform adequately under realistic conditions? Designing the evaluation around the requirements keeps the chain tight, problem to design to evaluation, and makes it harder to evaluate for things that were never required.'),
    spacer(),
    pb(),

    h1('Chapter 3 (Extended): Extended System Evaluation'),
    spacer(),
    h2('3.5 Think-Aloud Usability Testing'),
    body('Think-aloud testing asks participants to verbalise their thoughts continuously while completing tasks. Developed in cognitive psychology by Ericsson and Simon (1984) and widely used in HCI research, the method surfaces the mental models users form when they encounter an unfamiliar interface. Its advantage over post-task questionnaires is that confusion is captured in the moment, users cannot rationalise it away or forget it before they fill in a form.'),
    spacer(),
    body('Five participants were recruited. Each needed at least six months of experience managing inventory in a small business and to be comfortable using web applications. No familiarity with Ma5zony was required, unfamiliarity was actually preferable, since the goal was to evaluate discoverability and learnability, not expert proficiency. Participant characteristics are shown in Table 3.1.'),
    spacer(),
    makeTable(
      ['Participant', 'Business Sector', 'Inventory Exp. (yrs)', 'Current Tool'],
      [
        ['P1', 'Electronics retail', '4', 'Excel'],
        ['P2', 'Food distribution', '7', 'Paper + phone'],
        ['P3', 'Clothing wholesale', '3', 'Excel + WhatsApp'],
        ['P4', 'Hardware retail', '5', 'Basic POS system'],
        ['P5', 'Cosmetics e-commerce', '2', 'Shopify admin only'],
      ],
      [1500, 3000, 2000, 2860]
    ),
    caption('Table 3.1: Think-aloud participant characteristics'),
    spacer(),
    body('Each session opened with a brief orientation: no right or wrong answers, the researcher is evaluating the system not the participant, confusion is useful data. The participant then worked through a printed task list while thinking aloud. The researcher stayed silent except to prompt continued verbalisation ("what are you thinking right now?") or to intervene when someone was completely stuck for more than two minutes.'),
    spacer(),
    body('The task list covered seven scenarios: adding a product, recording a week of sales, running a demand forecast, reviewing replenishment recommendations, creating a purchase order, connecting a Shopify store, and finding the financial analytics dashboard. These were chosen to cover the main workflow and hit at least one task per major module.'),
    spacer(),
    body('Recordings were coded using a simplified version of the Boren and Ramey (2000) scheme. Each verbalisation was labelled as task-directed, evaluative, explanatory, or confused. The proportion of confused verbalisations per task was the primary usability signal.'),
    spacer(),
    h2('3.6 Task Completion and Error Analysis'),
    body('Four of the five participants completed all seven tasks without researcher intervention. The exception was P2, the participant with the least web application experience, who needed one intervention during the Shopify connection task. They were unsure whether the input expected a store URL or a store name, and the field label did not clarify this. That finding triggered a post-session change to the placeholder text: "yourstore.myshopify.com" rather than "Store URL".'),
    spacer(),
    body('The purchase order creation task had the highest error rate, three participants tried to create a purchase order before they had added a supplier, which the data model does not allow. The interface gave no indication of this ordering constraint. A post-session fix added an explanatory note to the purchase order screen: "You must add at least one supplier before creating a purchase order." It is a simple change but one that would not have surfaced without watching real users attempt the task.'),
    spacer(),
    body('Several positive characteristics emerged without having been specifically designed for. Multiple participants commented on the days-of-stock indicator; P3 said directly: "I really like that it shows me the number, I can see at a glance which products are running out." P5 noted that the colour-coded reorder badges made the dashboard readable without requiring them to look at individual values. These observations support the decision to use status-based colour encoding rather than raw numbers alone.'),
    spacer(),
    h2('3.7 System Usability Scale Results'),
    body('Each participant completed the System Usability Scale (SUS) after the session. Developed by Brooke (1996), the SUS is a ten-item questionnaire that produces a score from 0 to 100. Scores above 68 are considered above average; above 80 is excellent. The benchmark for "best imaginable" starts around 85-90.'),
    spacer(),
    makeTable(
      ['Participant', 'SUS Score', 'Qualitative Rating'],
      [
        ['P1', '82.5', 'Excellent'],
        ['P2', '72.5', 'Good'],
        ['P3', '87.5', 'Excellent'],
        ['P4', '85.0', 'Excellent'],
        ['P5', '90.0', 'Best Imaginable'],
      ],
      [2000, 2000, 5360]
    ),
    caption('Table 3.2: System Usability Scale scores'),
    spacer(),
    body('The mean score was 83.5, which sits in the excellent range. P2\'s score of 72.5 reflects the Shopify connection difficulty and their general unfamiliarity with browser-based tools. P5\'s 90.0 makes sense in context, as an e-commerce operator already accustomed to Shopify-like interfaces, the Ma5zony visual language felt familiar from the start.'),
    spacer(),
    body('Item-level analysis flagged one item consistently rated lower than the rest: item 8, "I found the system very cumbersome to use," averaged 3.2 out of 5. Digging into the think-aloud transcripts, the source seems to be the purchase order creation flow, multiple screens, several required fields, no shortcut for the common case of reordering the recommended quantity from an existing supplier. A quick-create modal that handles that case in one step would likely raise this score in a follow-up evaluation.'),
    spacer(),
    h2('3.8 Performance Benchmarking'),
    body('Performance was benchmarked across initial page load time, Firestore read latency, and Cloud Functions cold start duration. Measurements used Chrome DevTools with 4x CPU throttling and Fast 3G network throttling, conditions that approximate a mid-range mobile device on a reasonable connection, which is where much of the target user base would access the system.'),
    spacer(),
    body('Initial page load (first byte to time-to-interactive) measured 3.2 seconds on first visit and 1.1 seconds on return visits. The first-visit cost is driven by the Flutter web bundle at approximately 1.8 MB compressed. For a B2B productivity tool accessed from a fixed workstation, this is acceptable, users are not expecting instant load, but code splitting and lazy loading of non-critical modules would bring it down meaningfully.'),
    spacer(),
    body('Firestore initial data load, products, suppliers, warehouses, and user profile, averaged 340 milliseconds from authentication resolution to data available in the UI. This was measured with approximately 50 products, 10 suppliers, and 3 warehouses. The parallel listener architecture keeps this from scaling linearly with dataset size: each collection listener runs independently, so total load time is bounded by the slowest collection, not their sum.'),
    spacer(),
    body('The Shopify OAuth callback function had an average cold start of 1,400 milliseconds, driven by the Node.js initialisation time with several npm dependencies. That latency is acceptable for an operation that happens once per store setup. Warm instance invocations averaged 280 milliseconds, well within the expected range for a background API call.'),
    spacer(),
    pb(),
  ];
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 2: Security Analysis
// ─────────────────────────────────────────────────────────────────────────────
function securityAnalysis() {
  return [
    h1('Chapter 4 (Extended): Security Architecture and Threat Analysis'),
    spacer(),
    h2('4.12 Threat Modelling'),
    body('Security was treated as a design requirement from the start, not something to retrofit. The system handles sensitive business data, inventory levels, supplier relationships, Shopify store credentials, financial figures, and processes personal data in a way that triggers GDPR obligations. Leaving security for later would have meant either accepting known risks at launch or rearchitecting the data model after the fact, which is significantly harder. The threat modelling process used STRIDE (Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege) to work through threats per component.'),
    spacer(),
    body('The most significant attack surface is Firestore. Firebase\'s client SDKs allow direct database access from browser code, which means any client that has the Firebase configuration object, which is embedded in the application bundle and therefore not secret, can technically attempt to query any Firestore document. The only thing standing between a malicious actor and another user\'s data is the Firestore Security Rules, evaluated server-side for every read and write.'),
    spacer(),
    body('For Ma5zony, the security rules enforce user-scoped access through one core invariant: all data lives under users/{uid}/, and only requests authenticated with the matching uid are permitted. The top-level rule is: match /users/{userId}/{document=**} { allow read, write: if request.auth != null && request.auth.uid == userId; }. The wildcard {document=**} makes this recursive, no subcollection can accidentally be left open.'),
    spacer(),
    body('Role-based access control is enforced at two levels. In Firestore, write operations on financial data and role management are restricted to users whose document carries role: "owner", checked inline using get(). In the Flutter application, role_guard.dart prevents navigation to owner-only routes for other roles. The two layers together mean that bypassing the client-side navigation guard, by manually entering a URL, for example, still results in a denial at the Firestore level.'),
    spacer(),
    h2('4.13 Authentication Security'),
    body('Authentication is delegated entirely to Firebase Authentication, which handles bcrypt password hashing, authentication rate limiting, and optional multi-factor authentication. Delegating this rather than implementing it directly sidesteps the category of vulnerabilities that most commonly appear in home-rolled auth systems: improper password storage, weak session token generation, and missing token invalidation paths.'),
    spacer(),
    body('Firebase Authentication issues JWTs signed with Firebase\'s private key and verified by the Firebase Admin SDK server-side. A forged or tampered token fails verification and is rejected. Tokens expire after one hour; the SDK refreshes them automatically using a long-lived refresh token stored in IndexedDB, and that refresh token is rotated on each use.'),
    spacer(),
    body('The Shopify OAuth flow requires particular care because the Shopify access token must never reach client-side code. The entire flow runs through Cloud Functions: the token arrives at the Cloud Function during the OAuth callback and is written directly to Firestore on the server side. The Flutter application never sees it. Subsequent Shopify API calls are made from Cloud Functions that retrieve the token from Firestore server-side, so at no point does the access token travel through the browser.'),
    spacer(),
    h2('4.14 Input Validation and Injection Prevention'),
    body('All user inputs are validated client-side using Flutter\'s form validation before being written to Firestore. Numeric fields, quantities, prices, lead times, must be positive and within reasonable bounds. Text fields are trimmed before storage. These validations catch the obvious data quality issues; they are not the primary defence against malicious input.'),
    spacer(),
    body('Firestore is not vulnerable to SQL injection in the traditional sense because queries are built programmatically through the SDK\'s typed query builder, there is no mechanism for user input to alter query structure. The analogous concern in Firestore is rule bypass through crafted document paths, which the recursive wildcard rule addresses.'),
    spacer(),
    body('Shopify webhook handlers verify the HMAC-SHA256 signature on every incoming payload before processing it. Shopify signs each webhook request using the app\'s API secret; the Cloud Function checks this signature against the raw request body. Without this check, a malicious actor could POST forged webhook payloads and inject fraudulent order data into the system.'),
    spacer(),
    h2('4.15 Data Privacy and GDPR Compliance'),
    body('Ma5zony processes personal data in a few contexts: user account information, Shopify customer data embedded in imported orders, and employee data where the SME uses role-based access features. Under the GDPR, Ma5zony is a data processor acting on behalf of the SME (the data controller), and the SME is the controller for its own customers\' data.'),
    spacer(),
    body('The privacy architecture limits personal data retention deliberately. Shopify order imports pull only the data needed for inventory, line items, quantities, order dates, and do not import customer names or addresses. As a result, Ma5zony\'s Firestore database does not hold Shopify customer personal data, which removes a significant category of GDPR obligations. User account data lives in Firebase Authentication, which provides a deletion API; deleting a Firebase user account orphans all associated Firestore data under that uid, making it inaccessible under the security rules.'),
    spacer(),
    body('Full GDPR compliance for users in the European Economic Area requires a Data Processing Amendment executed with Google. Google provides a standard DPA for Firebase customers covering its obligations as a cloud processor. This agreement needs to be in place before Ma5zony is made available to EEA users at any scale.'),
    spacer(),
    pb(),
  ];
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 3: Business Analysis
// ─────────────────────────────────────────────────────────────────────────────
function businessAnalysis() {
  return [
    h1('Chapter 10: Business Analysis and Market Context'),
    spacer(),
    h2('10.1 Market Size and Opportunity'),
    body('SMEs account for roughly 90% of businesses and over 50% of employment worldwide, according to the World Bank\'s 2023 Small Business Report. That scale should translate into a well-served software market. It does not. The tools available for SME inventory management sit at opposite ends of a spectrum: simple point-of-sale systems with basic stock tracking on one side, and ERP systems priced at tens of thousands of pounds per year on the other. The middle, affordable tools with real analytical capability, is largely empty.'),
    spacer(),
    body('The inventory management software market was valued at approximately USD 3.2 billion in 2023 and is projected to reach USD 5.1 billion by 2028, growing at 9.8% CAGR (MarketsandMarkets, 2023). The fastest-growing segment is cloud-based SaaS targeted at SMEs, driven by the spread of e-commerce, falling cloud infrastructure costs, and SME operators becoming more comfortable with subscription software.'),
    spacer(),
    body('Within the Shopify ecosystem specifically, the numbers are striking. As of 2024, Shopify hosts over 1.75 million merchants, almost all of them small businesses. The App Store has over 8,000 apps, around 400 of which address inventory in some form. That density shows both the demand and the competitive intensity. Ma5zony\'s differentiation is the combination of demand forecasting, ABC-XYZ matrix analysis, and manufacturing workflow. No current Shopify inventory app offers all three.'),
    spacer(),
    h2('10.2 Competitive Landscape'),
    body('Competitors in this space fall into three broad groups: simple stock trackers, demand planning tools, and full ERP integrations.'),
    spacer(),
    body('Simple stock trackers, Stocky (acquired by Shopify, now free for POS users) and Craftybase (aimed at handmade product businesses), handle real-time stock levels and basic reorder alerts. They work well for businesses with stable, simple demand. They provide nothing useful when demand becomes variable or seasonal.'),
    spacer(),
    body('Demand planning tools like Inventory Planner and Cogsy offer more capable forecasting, seasonality adjustment, multi-location support, but they are priced at USD 99-199 per month for entry-level plans. That rules out many micro-enterprises on budget alone. They also do not touch manufacturing or the raw materials / finished goods distinction. And critically, their forecasts are presented without explanation, which the Ma5zony user research confirmed is a serious trust barrier.'),
    spacer(),
    body('Full ERP systems like NetSuite and SAP Business One have the functionality but at USD 1,000-2,000 per month plus implementation costs, and with complexity that makes them impractical for a ten-person business. A typical SME ERP implementation takes three to six months and requires a consultant. That is not a realistic path for the businesses Ma5zony targets.'),
    spacer(),
    makeTable(
      ['Competitor', 'Price/Month', 'Forecasting', 'ABC-XYZ', 'Manufacturing', 'Transparency'],
      [
        ['Stocky', 'Free', 'None', 'No', 'No', 'N/A'],
        ['Craftybase', '$19', 'Basic', 'No', 'Basic', 'Low'],
        ['Inventory Planner', '$99+', 'Advanced', 'No', 'No', 'Low'],
        ['Cogsy', '$119+', 'Advanced', 'No', 'No', 'Low'],
        ['NetSuite', '$1,000+', 'Advanced', 'Yes', 'Yes', 'Medium'],
        ['Ma5zony', 'TBD (SaaS)', 'SMA + SES', 'Yes', 'Yes', 'High'],
      ],
      [2000, 1500, 1500, 1200, 1800, 1360]
    ),
    caption('Table 10.1: Competitive comparison'),
    spacer(),
    body('Ma5zony sits in the gap between Craftybase and Inventory Planner: more capable than the affordable tools, far cheaper and simpler than the enterprise options, and differentiated from both by the transparency of its algorithmic outputs. This is consistent with the blue-ocean strategy concept (Kim and Mauborgne, 2005), rather than competing on Inventory Planner\'s terms (forecasting sophistication) or Stocky\'s terms (price), Ma5zony occupies a configuration that no existing competitor offers.'),
    spacer(),
    h2('10.3 Revenue Model and Pricing Strategy'),
    body('The planned model is a tiered SaaS subscription with three plans. The Starter plan gives solo operators core inventory tracking and basic forecasting for a limited product count. The Growth plan adds the full forecasting suite, ABC-XYZ analysis, Shopify integration, and multi-user support. The Professional plan adds manufacturing workflow, financial analytics, supplier portal access, and priority support. The tiering allows businesses to enter at low cost and upgrade as confidence in the product grows, rather than paying upfront for features they may never use.'),
    spacer(),
    body('Exact pricing is not finalised, but competitive benchmarking points to a Growth plan around USD 39-59 per month. At that price point, 100 paying Growth customers generates USD 4,700-7,100 per month in recurring revenue. Firebase infrastructure at that scale would run approximately USD 200-400 per month, leaving a meaningful margin to fund ongoing development.'),
    spacer(),
    body('The primary acquisition channel is the Shopify App Store, which surfaces the app organically to merchants already searching for inventory solutions. Shopify\'s partner programme requires meeting quality and security standards that Ma5zony\'s current architecture satisfies. A secondary channel is direct outreach through Shopify merchant communities, where the ABC-XYZ matrix and transparent forecasting are likely to resonate with operators who already think analytically about their stock.'),
    spacer(),
    h2('10.4 Scalability and Operational Considerations'),
    body('The Firebase architecture scales well for the early growth phases. Firestore scales horizontally without configuration: each additional customer\'s data is independently sharded by Firebase\'s infrastructure, so growth does not require provisioning new database capacity. Cloud Functions scale the same way, each invocation runs in an independent container, provisioned and terminated automatically.'),
    spacer(),
    body('The main scalability concern is Firestore read costs. The real-time listener architecture incurs a read charge for every document delivered. For a business with 1,000 products and 100 monthly active users, read costs could reach USD 50-100 per month. That is manageable at the planned price point but needs monitoring. As the user base grows, pagination, client-side caching of stable data, and batch reads for reporting will likely be needed to keep costs in check.'),
    spacer(),
    body('Operationally, Ma5zony currently needs no dedicated infrastructure staff. Firebase and Cloud Functions manage themselves; the application is a static web bundle served from Firebase Hosting with no servers to patch. That zero-operations model is essential for a solo-developer product at this stage. Operational needs will grow with the customer base, support, billing, monitoring, but those can all be handled through existing SaaS tools rather than bespoke infrastructure.'),
    spacer(),
    pb(),
  ];
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 4: Extended Future Work
// ─────────────────────────────────────────────────────────────────────────────
function extendedFutureWork() {
  return [
    h1('Chapter 9 (Extended): Future Work and Development Roadmap'),
    spacer(),
    h2('9.5 Machine Learning Integration'),
    body('The forecasting module uses Simple Moving Average and Simple Exponential Smoothing. These are the right starting point: computationally lightweight, explainable in plain language, and usable with relatively few historical data points. But they have real limitations. Strong seasonal patterns, external factors like marketing campaigns, and multi-cycle demand behaviour are all things they handle poorly.'),
    spacer(),
    body('The first upgrade on the roadmap is Holt-Winters seasonal smoothing, already described as a theoretical extension in the dissertation. It adds additive or multiplicative seasonality on top of the SES framework without changing the user\'s mental model fundamentally. A food retailer whose demand spikes around Ramadan and Eid, or a sports retailer whose sales depend on which leagues are in season, would get materially better forecasts from Holt-Winters than from plain SES.'),
    spacer(),
    body('The longer-term direction is gradient boosting models, XGBoost or LightGBM, that can incorporate external features alongside historical demand. Shopify\'s API exposes marketing campaign data, discount periods, and product page view counts. A merchant running a 20% discount every Black Friday would benefit from a model that explicitly accounts for that discount, rather than treating the November demand spike as unexplained noise that degrades forecast accuracy.'),
    spacer(),
    body('The practical challenge is not algorithmic, it is data. Training a seasonal model requires at least a year of weekly data, and ideally two or more. Most Ma5zony users will not have that when they start. The roadmap includes a "model graduation" feature: new users start on SMA, transition to SES automatically after 12 weeks of data, and are offered ML-based forecasting once 52 weeks of data are available. This prevents the system from presenting overconfident ML predictions to users whose data cannot support them.'),
    spacer(),
    h2('9.6 Mobile Application Development'),
    body('The current implementation targets web browsers, with responsive design that works reasonably well on tablets. A dedicated mobile application would unlock things that browsers cannot do well: barcode scanning for stock checks and receiving, native push notifications for reorder alerts, and offline-capable stock counting that syncs when connectivity returns.'),
    spacer(),
    body('Flutter\'s cross-platform architecture means the mobile app can be built from the same codebase. The core business logic, forecasting, replenishment, the Firestore data layer, needs no changes. Platform-specific features like camera access for scanning and native notification channels go through Flutter\'s platform channel mechanism. The development effort is concentrated in designing a mobile-optimised UI for stock management workflows and wiring up the hardware integrations.'),
    spacer(),
    body('Barcode scanning is particularly valuable for the manufacturing workflow. Currently, when a raw material delivery arrives, the receiving clerk has to navigate to the order in the web interface and manually confirm receipt. With a mobile app, they could scan the delivery barcode, see the expected quantity, and confirm with a single tap. That reduces both the time and the error rate in the receiving process and gives a more accurate real-time view of raw material inventory.'),
    spacer(),
    h2('9.7 Multi-Tenancy and White-Label Architecture'),
    body('The current architecture is single-tenant: each Firebase project instance holds one customer\'s data. That is fine for now, but it does not scale well, each new customer would require a separate Firebase project, with all the configuration and maintenance overhead that implies.'),
    spacer(),
    body('A multi-tenant architecture would store all customers\' data in a single Firebase project, with Firestore Security Rules enforcing data isolation between tenants. The data model shifts from users/{uid}/... to organisations/{orgId}/members/{uid}/... and organisations/{orgId}/data/..., with the organisation ID as the primary tenant key. Security rules verify that the authenticated user is a member of the organisation whose data they are requesting.'),
    spacer(),
    body('Multi-tenancy also enables white-label deployment. An agency or inventory consultancy could offer Ma5zony\'s capabilities under their own brand to their clients, with colour scheme, logo, and application name configurable through an organisation-level settings document. One codebase, one Firebase project, multiple branded deployments.'),
    spacer(),
    h2('9.8 Advanced Analytics and Reporting'),
    body('The financial analytics module shows cash flow in real time based on purchase order costs and Shopify revenue. Useful operationally, but it does not give a growing business what it needs for strategic decisions. The roadmap adds several layers.'),
    spacer(),
    body('Product profitability analysis would compute gross margin per product by combining the cost of goods sold, derived from supplier prices in the purchase order history, against the selling price from Shopify order data. Knowing which products are most and least profitable is currently very difficult to establish without building a custom spreadsheet model. Ma5zony would update this automatically each time new Shopify data arrives.'),
    spacer(),
    body('Cohort analysis of demand patterns would let users compare demand across periods with similar characteristics: the same month across multiple years, periods before and after a marketing campaign, weekday versus weekend demand. This type of analysis is standard in e-commerce analytics platforms but is missing from every current Shopify inventory management tool.'),
    spacer(),
    body('Supplier performance analytics would track lead time variability, fulfilment rates, and price changes per supplier over time. A supplier who consistently delivers two days late inflates safety stock requirements and raises stockout risk, quantifying this gives the owner concrete grounds to renegotiate or switch. No SME-targeted inventory tool currently offers this.'),
    spacer(),
    h2('9.9 Integration Ecosystem Expansion'),
    body('Shopify is the only platform integrated today. The roadmap adds WooCommerce (used by roughly 28% of online stores), Amazon Seller Central, and accounting platforms like QuickBooks and Xero, to eliminate the manual reconciliation that currently bridges Ma5zony\'s inventory costs to financial accounts.'),
    spacer(),
    body('Each integration follows the same architectural pattern as Shopify: Cloud Functions-based OAuth, a scheduled or webhook-triggered import function, and a normalisation layer mapping the external platform\'s data model to Ma5zony\'s internal models. The normalisation layer is the hardest part, a Shopify variant, a WooCommerce attribute combination, and an Amazon ASIN variation all refer to the same concept, but they are represented differently and identified differently across APIs.'),
    spacer(),
    body('The long-term vision is a unified inventory intelligence layer sitting above all of an SME\'s operational platforms: pulling demand signals from multiple sales channels, aggregating them into a single demand model, and generating replenishment recommendations that account for stock across all fulfilment channels. The most sophisticated e-commerce operators already work this way. The challenge is building it at a cost and complexity level that a ten-person business can actually use.'),
    spacer(),
    pb(),
  ];
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 5: Personal Reflections and Critical Evaluation
// ─────────────────────────────────────────────────────────────────────────────
function extendedReferences() {
  return [
    h1('Chapter 11: Personal Reflections and Critical Evaluation'),
    spacer(),
    h2('11.1 Reflections on the Development Process'),
    body('Looking back on eighteen months of building Ma5zony, the most useful things I learned were not technical. The technical problems, Firestore data modelling, the forecasting algorithms, the Shopify OAuth flow, were hard, but they had correct answers. I could find those answers by reading, experimenting, and debugging. The genuinely difficult part was deciding what to build, in what order, and why.'),
    spacer(),
    body('The biggest single decision was to prioritise the manufacturing workflow over a mobile application. Manufacturing addresses a narrower use case, businesses that produce goods rather than just trade them, but it creates differentiation from every existing Shopify inventory tool. A mobile app would have been more broadly applicable but would have left Ma5zony as a capable, undifferentiated stock tracker. Going deep on manufacturing rather than broad on platform coverage was a conscious bet on a specific type of user.'),
    spacer(),
    body('One conversation made that decision feel right. I described the planned manufacturing workflow to a potential user who runs a cosmetics business, she formulates her own products. Her response was immediate: she had been managing raw material inventory in a separate Excel file, calculating by hand how many finished units she could produce from available stock, and there was nothing on the market that did this for her. That conversation clarified the value proposition more sharply than any amount of market research had done.'),
    spacer(),
    body('The technical decision I would make differently is the Firestore listener architecture. Using a persistent real-time listener per collection across the entire application lifetime works beautifully when the dataset is small. But as the product list grows past a few hundred items, the listener starts consuming meaningful read quota and browser memory. A pagination-based approach, loading the most urgent products first and fetching more on demand, would have been more scalable from the start, even though it would have added complexity to the state management layer. I understood this trade-off at the time and chose simplicity; I still think that was right for the early phase, but I underestimated how quickly a real business would push against the limits.'),
    spacer(),
    h2('11.2 Limitations of the Current Implementation'),
    body('The usability study had five participants, all recruited through the developer\'s personal network. That is a convenience sample, and it introduces bias: people who agreed to participate may be more sympathetic to the product than a random sample of SME operators would be. The small size also limits how far the findings can be generalised. A more rigorous evaluation would use a larger sample recruited through a neutral channel, a trade association, an online panel, or a Shopify merchant community.'),
    spacer(),
    body('The evaluation also captures usability at a single point in time. It tells you whether someone can figure out how to use the system on their first encounter; it cannot tell you how quickly they become proficient over weeks of actual use, or which features they end up ignoring. A longitudinal study, giving participants access to the system for a month and interviewing them periodically, would reveal the adoption patterns and expert behaviours that a one-hour session cannot surface.'),
    spacer(),
    body('The performance benchmarks were measured in a controlled environment with simulated throttling. Real-world performance depends on actual device hardware, network conditions, and dataset size in ways that are hard to replicate in a lab. The Firestore latency figures in particular were measured against a small dataset; I have not evaluated how the system performs with thousands of products and years of demand history. That is a real gap in the evaluation, and one that needs to be addressed before a serious commercial launch.'),
    spacer(),
    h2('11.3 Contribution to Knowledge'),
    body('This dissertation offers a detailed case study in applying Design Science Research to a solo software development project with limited resources, demonstrating how the three DSR cycles can be operationalised in practice, not just described in the abstract. The relevance cycle is often glossed over in student projects; here it drove substantive design decisions before a line of code was written.'),
    spacer(),
    body('The transparent forecasting interface is a concrete design contribution. The finding that SME users will not trust algorithmic recommendations they cannot interrogate is not new, it appears in the literature on decision support systems, but the specific implementation pattern here (showing the input data, the formula, and the result together) is a practical response to that finding that could be reused in any domain where algorithmic outputs need to be communicated to non-expert users.'),
    spacer(),
    body('The architectural contribution is demonstrating that a manufacturing-aware inventory system, one that distinguishes raw materials from finished goods, tracks bill-of-materials relationships, and generates replenishment recommendations at both levels, can be built on Firebase\'s serverless infrastructure without a dedicated application server. That matters for cost and operational complexity in a segment where neither can be taken for granted.'),
    spacer(),
    h2('11.4 Academic and Professional Context'),
    body('This project was the final year graduation project for the Bachelor of Science in Computer Science programme at the British University in Egypt. It represents roughly 600 hours of development, research, and documentation across two semesters. The scope was set deliberately to require skills from multiple modules: software engineering, database systems, human-computer interaction, and business computing. Writing a dissertation that had to connect all of those was harder than working in any one of them alone, and more useful.'),
    spacer(),
    body('Ma5zony is not a demonstration system. It is deployed on Firebase, has a real domain, and has real users whose data it holds. That distinction matters. A system built purely for assessment can be designed around the marking criteria; a system with real users has to be designed around their needs. Every decision in this dissertation, from the Firestore data model to the transparent forecasting interface to the security rules, was made under that constraint. It is a different kind of accountability, and a more useful one to develop.'),
    spacer(),
    body('Building Ma5zony confirmed something I had been developing a view on throughout the degree: the most valuable software is not the most technically impressive, but the software that fits naturally into how someone already works and makes something genuinely difficult a little bit easier. Inventory management for small businesses is not a glamorous problem. But it is a real one, affecting millions of businesses, and the existing tools are genuinely inadequate for most of them. If Ma5zony helps even a small number of those businesses make better decisions about their stock, that is a more satisfying outcome than building something technically sophisticated that no one actually uses.'),
    spacer(),
    pb(),
  ];
}

module.exports = {
  extendedMethodology,
  extendedEvaluation: extendedMethodology,
  securityAnalysis,
  businessAnalysis,
  extendedFutureWork,
  extendedReferences,
};
