
// Chapters 3 & 4: Requirements + Architecture
const { h1, h2, h3, body, bodyBold, code, caption, pb, spacer, makeTable } = require('./generate_report_p1');
const { Paragraph, TextRun, AlignmentType } = require('docx');

function chapter3() {
  return [
    h1('Chapter 3: Requirements Analysis'),
    spacer(),
    h2('3.1 Stakeholder Identification'),
    body('The primary stakeholders for Ma5zony are the SME owners and their inventory management staff who will use the system on a daily basis. Secondary stakeholders include the suppliers, manufacturers, and raw-material factories who interact with the system through the public portal interfaces, and the developers who will maintain and extend the codebase after initial deployment.'),
    spacer(),
    body('Informal requirements-gathering conversations with three small-business operators during the early stages of the project surfaced a consistent set of pain points. The first was that existing tools required too much data entry before they produced any useful output. Several participants described abandoning a system after spending days entering product data only to find the forecasting module was disabled until historical demand data was also entered. The second pain point was supplier management: participants wanted a way to track which suppliers provided which products, with lead time information included, so that ordering decisions could account for delivery time automatically. The third was manufacturing cost visibility: two of the three participants ran businesses that manufactured at least some of their products from raw materials, and neither had a systematic way to track the cost of production at the per-unit level.'),
    spacer(),
    h2('3.2 Functional Requirements'),
    body('The following functional requirements were derived from the literature review and the stakeholder conversations, and form the basis against which the final system was evaluated.'),
    spacer(),
    makeTable(
      ['ID', 'Requirement', 'Priority'],
      [
        ['FR-01', 'The system shall allow SME owners to register, log in, and manage their account credentials', 'Must'],
        ['FR-02', 'The system shall support four user roles: SME Owner, Inventory Manager, Manufacturer, Raw Material Factory', 'Must'],
        ['FR-03', 'The system shall allow users to create, read, update, and delete product records including SKU, unit cost, and current stock level', 'Must'],
        ['FR-04', 'The system shall allow users to manage supplier records with contact details and typical lead time', 'Must'],
        ['FR-05', 'The system shall allow users to manage warehouse records and assign products to warehouses', 'Must'],
        ['FR-06', 'The system shall allow demand data to be entered manually by period', 'Must'],
        ['FR-07', 'The system shall import product catalogue and order history from Shopify via OAuth', 'Must'],
        ['FR-08', 'The system shall implement SMA, WMA, SES, Holt, and Holt-Winters forecasting algorithms', 'Must'],
        ['FR-09', 'The system shall display forecast accuracy metrics (MAE, MAPE, RMSE) alongside results', 'Must'],
        ['FR-10', 'The system shall generate automatic replenishment recommendations using ROP and safety stock theory', 'Must'],
        ['FR-11', 'The system shall generate purchase orders from approved recommendations', 'Must'],
        ['FR-12', 'The system shall support bill-of-materials definition linking finished products to raw materials', 'Must'],
        ['FR-13', 'The system shall generate production orders for manufactured products via the BOM', 'Must'],
        ['FR-14', 'The system shall compute ABC-XYZ product classification from demand history', 'Should'],
        ['FR-15', 'The system shall provide public token-based portals for suppliers, manufacturers, and factories', 'Should'],
        ['FR-16', 'The system shall send email notifications to suppliers and manufacturers when orders are placed', 'Should'],
        ['FR-17', 'The system shall display a cash flow projection based on pending orders and product costs', 'Should'],
        ['FR-18', 'The system shall provide an interactive onboarding tour for new users', 'Should'],
        ['FR-19', 'The system shall log all significant workflow actions in an append-only audit trail', 'Could'],
        ['FR-20', 'The system shall support Progressive Web App installation on desktop and mobile', 'Could'],
      ],
      [800, 6360, 1200]
    ),
    caption('Table 3.1: Functional Requirements with MoSCoW priority classification'),
    spacer(),
    h2('3.3 Non-Functional Requirements'),
    body('In addition to the functional requirements above, the following non-functional requirements shaped the architecture and implementation choices:'),
    spacer(),
    body('Performance: The application should respond to user interactions within 200ms for locally computed operations (forecasting, recommendation generation). Operations involving Cloud Functions may take up to 10 seconds on cold start; these should be indicated with progress indicators.'),
    spacer(),
    body('Security: All authenticated API endpoints must verify a valid Firebase ID token. Firestore security rules must enforce user-scoped data access at the database level, independent of application-layer code. Shopify access tokens must be stored server-side and never exposed to the client. Portal access must be controlled by cryptographically random, time-limited tokens of at least 32 characters.'),
    spacer(),
    body('Reliability: The application must function correctly after a browser refresh without requiring re-login for sessions that have not expired. Cloud Functions must include error handling that returns meaningful HTTP status codes and descriptive error messages.'),
    spacer(),
    body('Usability: A user with no prior knowledge of the system should be able to complete initial setup and run their first forecast within 60 minutes of registration, following the interactive tour. Error states must provide actionable guidance rather than generic messages.'),
    spacer(),
    body('Maintainability: The codebase should follow consistent conventions and be structured such that a new developer can navigate to any feature implementation within five minutes of reading the project README.'),
    spacer(),
    h2('3.4 Use Case Summary'),
    body('The primary use cases can be grouped into five categories. The Setup category covers the initial configuration of products, suppliers, warehouses, and Shopify connection. The Demand Management category covers manual demand entry, Shopify order import, and demand data review. The Forecasting category covers running forecasts, reviewing accuracy metrics, and comparing algorithms. The Replenishment category covers reviewing recommendations, editing suggested order quantities, approving purchase orders, and approving manufacturing orders. The Administration category covers team management, notification preferences, and workflow log review.'),
    spacer(),
    body('Actor roles map to these categories as follows: the SME Owner can access all five categories and additionally sees financial analytics and cash flow projection. The Inventory Manager accesses Setup, Demand Management, Forecasting, and Replenishment but not financial details. Manufacturer and Raw Material Factory roles access only their respective portals via time-limited tokens.'),
    pb()
  ];
}

function chapter4() {
  return [
    h1('Chapter 4: System Architecture and Design'),
    spacer(),
    h2('4.1 System Overview'),
    body('Ma5zony follows a three-tier architecture: a Flutter web application running in the user\'s browser forms the presentation and application logic tier; Firebase services (Authentication, Firestore, Cloud Functions, and Hosting) form the data and backend tier; and the Shopify Admin API forms an external integration tier. This arrangement is shown schematically in the description below.'),
    spacer(),
    body('The Flutter client communicates directly with Firebase Authentication for login and session management, and directly with Firestore for all standard CRUD operations. It does not go through a conventional REST API server for these operations; the Firebase client SDKs embedded in the Flutter build handle the network communication. This architecture has important implications for security: because the client holds Firebase credentials, security must be enforced at the Firestore security rules layer rather than at an application server layer. This is discussed in detail in Section 4.5.'),
    spacer(),
    body('Cloud Functions are invoked selectively for operations that cannot be performed securely on the client: Shopify OAuth (because the Shopify API secret must never be exposed to a browser), email sending via SMTP (because SMTP credentials must also remain server-side), and any operation that requires elevated Firebase Admin SDK privileges. All Cloud Function endpoints verify a Firebase ID token from the Authorization header before performing any privileged operation.'),
    spacer(),
    makeTable(
      ['Component', 'Technology', 'Responsibility'],
      [
        ['Flutter Web Client', 'Flutter 3.x / Dart ^3.11.0', 'UI rendering, local state, Firestore reads/writes'],
        ['Firebase Authentication', 'Firebase Auth v5', 'User identity, session tokens, email/password auth'],
        ['Cloud Firestore', 'Firestore v5', 'NoSQL document storage, real-time listeners, security rules'],
        ['Cloud Functions v2', 'Node.js 22 / Cloud Run', 'Shopify OAuth, email dispatch, webhook handlers'],
        ['Firebase Hosting', 'Firebase Hosting', 'Static asset delivery, SPA rewrite rules, PWA config'],
        ['Shopify Admin API', 'GraphQL 2025-04', 'Product catalogue import, order history, inventory sync'],
        ['Sentry', 'sentry_flutter ^8.13.2', 'Error monitoring and performance tracing (optional)'],
      ],
      [2400, 2400, 4560]
    ),
    caption('Table 4.1: System components and their responsibilities'),
    spacer(),
    h2('4.2 Technology Stack Selection'),
    body('The choice of Flutter as the frontend framework was made early and held throughout the project. The key consideration was that the web target, while less mature than the mobile targets, allows the application to be deployed as a website without requiring platform store approval or native installation. For a B2B SaaS product targeting SME operators, a web application that can be accessed from any browser is significantly more practical than a mobile-first product.'),
    spacer(),
    body('Flutter\'s widget composition model, where every UI element is a widget and complex UIs are built by composing simpler ones, maps well to the feature-folder project structure used in Ma5zony. Each screen lives in its own folder under lib/features/, and the shared layout (the responsive sidebar and top bar) is encapsulated in lib/widgets/main_layout.dart. The Provider package for state management was chosen over alternatives such as Riverpod or BLoC because of its directness: a single ChangeNotifier subclass (AppState) holds all domain state, and widgets access it through context.watch<AppState>() or context.read<AppState>().'),
    spacer(),
    body('Firebase was chosen as the backend platform primarily because of its integration with Flutter through first-party Dart SDKs, its generous free tier, and the elimination of server infrastructure management. The decision to use Firestore over a relational database was consistent with the user-scoped data model: a NoSQL document store naturally accommodates the tree structure of users/{uid}/products/, users/{uid}/suppliers/, and so on, and Firestore\'s real-time listeners simplify the synchronisation of data between the Firestore backend and the in-memory state in AppState.'),
    spacer(),
    body('GoRouter v13 was selected for navigation because it supports declarative, URL-based routing that works correctly with the browser\'s back and forward buttons, which is essential for a web application. The deep-link pattern used for portal routes (/supplier-portal?token=..., /manufacturer-portal?token=..., /factory-portal?token=...) depends on URL parameter support that GoRouter provides cleanly.'),
    spacer(),
    h2('4.3 Application Architecture'),
    h3('4.3.1 State Management with AppState'),
    body('All application state lives in a single ChangeNotifier subclass, AppState, defined in lib/providers/app_state.dart. At approximately 1,900 lines, this is the largest single file in the project, and its size reflects both the breadth of functionality the system provides and the decision to centralise state management rather than distribute it across multiple providers.'),
    spacer(),
    body('AppState owns all service objects and instantiates them in its constructor. The key services are constructed unconditionally at startup:'),
    spacer(),
    code('AppState() {'),
    code('  _forecastingService = ForecastingService();'),
    code('  _policyService = InventoryPolicyService();'),
    code('  _replenishmentService = ReplenishmentService('),
    code('    forecastingService: _forecastingService,'),
    code('    policyService: _policyService,'),
    code('  );'),
    code('  _abcXyzService = AbcXyzService();'),
    code('  _authService = FirebaseAuthService();'),
    code('  _authService.authStateChanges.listen(_onAuthStateChanged);'),
    code('}'),
    spacer(),
    body('Services that require a user\'s uid (the Firestore repository, notification service, Shopify service) are initialised in _initRepo(String uid), which is called when authentication state changes indicate a successful login. This pattern ensures that Firestore reads never occur before a user is authenticated.'),
    spacer(),
    body('Widgets access state through two mechanisms. context.watch<AppState>() subscribes the widget to rebuild whenever AppState calls notifyListeners(). context.read<AppState>() retrieves the current AppState without subscribing, typically used in callbacks to invoke methods rather than read reactive state. This is a standard Provider pattern that keeps the widget tree decoupled from the specific data structures in AppState.'),
    spacer(),
    h3('4.3.2 Routing with GoRouter'),
    body('Routes are defined in lib/app_router.dart through a buildAppRouter(AppState appState) function that returns a configured GoRouter instance. The router uses a ShellRoute to wrap all authenticated screens in MainLayout (the sidebar shell), with portal routes and authentication routes defined outside the shell as top-level GoRoutes.'),
    spacer(),
    body('The router uses appState.authNotifier — a dedicated AuthNotifier ChangeNotifier — as its refreshListenable. This is a deliberate design decision: using the full AppState as the router\'s refreshListenable would cause the router to re-evaluate redirect logic on every notifyListeners() call, which happens on every CRUD operation. By separating auth-related notifications into AuthNotifier, the router only re-evaluates when the user actually logs in or out.'),
    spacer(),
    body('The complete route list is provided in Appendix A. Key routes include:'),
    spacer(),
    makeTable(
      ['Route', 'Component', 'Auth Required'],
      [
        ['/login', 'LoginScreen', 'No'],
        ['/register', 'RegisterScreen (invite token optional)', 'No'],
        ['/dashboard', 'OwnerDashboardScreen or DashboardScreen (role-based)', 'Yes'],
        ['/products', 'ProductsScreen', 'Yes'],
        ['/suppliers', 'SuppliersScreen', 'Yes'],
        ['/warehouses', 'WarehousesScreen', 'Yes'],
        ['/demand-data', 'DemandDataScreen', 'Yes'],
        ['/forecasts', 'ReorderPlanScreen (tabs: Forecast + Replenishment)', 'Yes'],
        ['/orders', 'OrdersScreen', 'Yes'],
        ['/orders/create', 'CreateOrderScreen', 'Yes'],
        ['/orders/:id', 'OrderDetailScreen', 'Yes'],
        ['/raw-materials', 'RawMaterialsScreen', 'Yes'],
        ['/bom', 'BomScreen', 'Yes'],
        ['/manufacturers', 'ManufacturersScreen', 'Yes'],
        ['/recommendations', 'RecommendationsScreen', 'Yes'],
        ['/production-orders', 'ProductionOrdersScreen', 'Yes'],
        ['/classification', 'AbcXyzScreen', 'Yes'],
        ['/cash-flow', 'CashFlowScreen (owner only)', 'Yes'],
        ['/financial-analytics', 'FinancialAnalyticsScreen (owner only)', 'Yes'],
        ['/integrations', 'IntegrationsScreen', 'Yes'],
        ['/settings', 'SettingsScreen', 'Yes'],
        ['/supplier-portal', 'SupplierPortalScreen (token param)', 'No'],
        ['/manufacturer-portal', 'ManufacturerPortalScreen (token param)', 'No'],
        ['/factory-portal', 'FactoryPortalScreen (token param)', 'No'],
      ],
      [2800, 3960, 1600]
    ),
    caption('Table 4.2: Application route map'),
    spacer(),
    h3('4.3.3 Service Layer'),
    body('The service layer sits between AppState and the data layer. Each service is a plain Dart class that contains business logic with no dependencies on Flutter widgets or Firebase directly. This makes them straightforwardly unit-testable and means the business logic can be understood without any knowledge of the UI framework.'),
    spacer(),
    makeTable(
      ['Service', 'File', 'Responsibility'],
      [
        ['FirestoreInventoryRepository', 'firestore_inventory_repository.dart', 'All Firestore CRUD for domain entities'],
        ['FirebaseAuthService', 'firebase_auth_service.dart', 'Authentication, registration, profile management'],
        ['ForecastingService', 'forecasting_service.dart', 'SMA, WMA, SES, Holt, Holt-Winters algorithms'],
        ['ReplenishmentService', 'replenishment_service.dart', 'Demand pipeline, ROP, safety stock, recommendations'],
        ['InventoryPolicyService', 'inventory_policy_service.dart', 'EOQ, ROP, and safety stock formula implementations'],
        ['DemandAggregationService', 'demand_aggregation_service.dart', 'Monthly aggregation and gap-filling of demand records'],
        ['AbcXyzService', 'abc_xyz_service.dart', 'ABC-XYZ classification matrix from demand data'],
        ['ManufacturingService', 'manufacturing_service.dart', 'Production order workflow and status transitions'],
        ['CashFlowService', 'cash_flow_service.dart', 'Cash position aggregation from orders and costs'],
        ['BackendApiService', 'backend_api_service.dart', 'HTTP client for optional external analytics backend'],
        ['FirebaseShopifyService', 'firebase_shopify_service.dart', 'Shopify OAuth token management via Cloud Functions'],
        ['NotificationService', 'notification_service.dart', 'In-app notifications (Firestore-backed real-time stream)'],
        ['WorkflowService', 'workflow_service.dart', 'Append-only audit trail for workflow actions'],
        ['SettingsService', 'settings_service.dart', 'User and global settings persistence'],
        ['RecommendationEngineService', 'recommendation_engine_service.dart', 'Manufacturing recommendation generation logic'],
        ['MinimumStockService', 'minimum_stock_service.dart', 'Minimum stock level calculations'],
        ['RawMaterialOrderService', 'raw_material_order_service.dart', 'Raw material purchase order generation from BOMs'],
        ['SupplyChainInsightsService', 'supply_chain_insights_service.dart', 'Cross-entity analytical insights aggregation'],
      ],
      [3200, 3000, 3160]
    ),
    caption('Table 4.3: Service layer components'),
    spacer(),
    h2('4.4 Data Architecture'),
    h3('4.4.1 Firestore Data Model'),
    body('All user-owned data is stored under a top-level users/{uid}/ document, which itself contains a profile and acts as the root of all subcollections for that user. This user-scoping pattern is the standard Firestore multi-tenancy approach; it naturally maps to the security model described in Section 4.5 and means that a complete backup or export of a single user\'s data is a simple subtree read.'),
    spacer(),
    body('Three collections — supplierOrders, manufacturerOrders, and factoryOrders — are stored at the top level (outside the users/ hierarchy) because they need to be accessible to portal users who do not have a Firebase Authentication session. These documents carry their own access control through the accessToken and expiresAt fields, validated in the Firestore security rules.'),
    spacer(),
    makeTable(
      ['Collection', 'Path', 'Key Fields'],
      [
        ['products', 'users/{uid}/products', 'sku, name, category, unitCost, currentStock, supplierId, manufacturerId, warehouseId, sourcingType, stockByWarehouse'],
        ['suppliers', 'users/{uid}/suppliers', 'name, contactEmail, phone, typicalLeadTimeDays, performanceRating'],
        ['warehouses', 'users/{uid}/warehouses', 'name, city, country, capacity'],
        ['demandRecords', 'users/{uid}/demandRecords', 'productId, periodStart, quantity, source (manual/shopify)'],
        ['purchaseOrders', 'users/{uid}/purchaseOrders', 'status, items[], supplierId, totalCost, createdAt'],
        ['rawMaterials', 'users/{uid}/rawMaterials', 'name, sku, unit, unitCost, supplierId, currentStock, safetyStock, leadTimeDays'],
        ['boms', 'users/{uid}/boms', 'finalProductId, materials:[{rawMaterialId, quantityPerUnit}]'],
        ['manufacturers', 'users/{uid}/manufacturers', 'name, contactEmail, productionCapacity, productionFeePerUnit'],
        ['productionOrders', 'users/{uid}/productionOrders', 'finalProductId, quantity, status, manufacturerId, estimatedCost'],
        ['forecastResults', 'users/{uid}/forecastResults', 'productId, algorithm, periods, forecast[], mae, mape, rmse'],
        ['replenishmentRecommendations', 'users/{uid}/replenishmentRecommendations', 'productId, currentStock, reorderPoint, suggestedOrderQty, urgency'],
        ['manufacturingRecommendations', 'users/{uid}/manufacturingRecommendations', 'productId, suggestedQty, estimatedCost, priority, status'],
        ['shopifyConnections', 'users/{uid}/shopifyConnections', 'shopDomain, connectedAt (token stored server-side)'],
        ['notifications', 'users/{uid}/notifications', 'type, title, message, relatedId, isRead, createdAt'],
        ['workflowLogs', 'users/{uid}/workflowLogs', 'action, entityId, entityType, performedBy, timestamp (append-only)'],
        ['settings', 'users/{uid}/settings', 'defaultAlgorithm, smaWindow, sesAlpha, holtBeta, serviceLevelTarget'],
        ['supplierOrders', 'supplierOrders/{id} (top-level)', 'accessToken, expiresAt, ownerUid, supplierId, items[], status'],
        ['manufacturerOrders', 'manufacturerOrders/{id} (top-level)', 'accessToken, expiresAt, ownerUid, productionOrderId, status'],
        ['factoryOrders', 'factoryOrders/{id} (top-level)', 'accessToken, expiresAt, ownerUid, rawMaterialOrderId, status'],
      ],
      [2400, 2960, 4000]
    ),
    caption('Table 4.4: Firestore collections and their key fields'),
    spacer(),
    h3('4.4.2 Product Sourcing Model'),
    body('One of the most important design decisions in the data model is the distinction between purchased and manufactured products. A purchased product is one the business buys from an external supplier; its unit cost is the purchase price from that supplier. A manufactured product is one the business produces from raw materials; its unit cost is derived from the bill of materials (sum of raw material quantities multiplied by their unit costs) plus the manufacturer\'s per-unit production fee.'),
    spacer(),
    body('This distinction, stored as the sourcingType field on the product document, drives a significant amount of downstream logic. Replenishment recommendations for purchased products generate purchase orders directed to the product\'s supplier. Replenishment recommendations for manufactured products open a bill-of-materials confirmation dialog, check raw material availability, and generate production orders alongside the raw material procurement orders.'),
    spacer(),
    body('The decision to make this distinction explicit in the data model rather than inferring it from the presence or absence of a BOM was a significant design evolution from the initial prototype. In the first version, products were assumed to be purchased unless a BOM existed. This created a confusing user experience because newly imported Shopify products defaulted to the purchased path and generated inappropriate supplier-linking prompts for items that were actually manufactured. The explicit sourcingType field, set through a dedicated Set Sourcing workflow early in the onboarding sequence, eliminated this ambiguity entirely.'),
    spacer(),
    h2('4.5 Security Architecture'),
    body('Security in Ma5zony operates at two distinct layers: Firebase Authentication for identity management, and Firestore security rules for data access control. The combination means that even if the application code contained a bug that attempted an unauthorised data read or write, the Firestore rules would reject the operation at the database level.'),
    spacer(),
    body('The security rules are defined in firestore.rules and deploy with firebase deploy --only firestore:rules. The rules define helper functions that encapsulate the access logic:'),
    spacer(),
    code('function isSignedIn() {'),
    code('  return request.auth != null;'),
    code('}'),
    code(''),
    code('function isOwner(userId) {'),
    code('  return isSignedIn() && request.auth.uid == userId;'),
    code('}'),
    code(''),
    code('function userRole() {'),
    code('  return get(/databases/$(database)/documents/users/$(request.auth.uid)).data.role;'),
    code('}'),
    code(''),
    code('function hasInventoryRole() {'),
    code('  return isSignedIn() && (userRole() == "SME Owner" || userRole() == "Inventory Manager");'),
    code('}'),
    spacer(),
    body('The isOwner(userId) function checks that the requesting user\'s uid matches the userId path parameter, ensuring that users can only access their own data subtree. The userRole() function performs a get() on the requesting user\'s profile document to retrieve their assigned role, which is then checked by hasInventoryRole() and hasOwnerRole().'),
    spacer(),
    body('The portal document access model uses a different mechanism because portal users do not have Firebase Authentication sessions. Portal collections (supplierOrders, manufacturerOrders, factoryOrders) use a portalDocValid() helper that validates the document\'s own accessToken field:'),
    spacer(),
    code('function portalDocValid() {'),
    code('  return resource.data.accessToken is string'),
    code('      && resource.data.accessToken.size() >= 32'),
    code('      && resource.data.expiresAt is timestamp'),
    code('      && resource.data.expiresAt > request.time;'),
    code('}'),
    spacer(),
    body('Portal writes are further restricted to specific field updates — a supplier portal can only update the response and status fields, preventing a portal user from modifying order items, access tokens, or any other sensitive fields.'),
    spacer(),
    h2('4.6 Cloud Infrastructure'),
    body('The production application is deployed to Firebase project ma5zony. Firebase Hosting serves the Flutter web build from the build/web directory, with a catch-all rewrite rule that directs all unmatched paths to /index.html — the standard Single Page Application configuration that allows GoRouter\'s client-side routing to function correctly.'),
    spacer(),
    body('Cloud Functions deploy to Google Cloud Run (us-central1) under the function naming convention documented in cloud_function_config.dart. Function names are lowercased in Cloud Run URLs regardless of how they are named in the JavaScript source. The deployed functions include:'),
    spacer(),
    makeTable(
      ['Function', 'Trigger', 'Purpose'],
      [
        ['shopifyGetOAuthUrl', 'HTTP POST', 'Generates Shopify OAuth authorisation URL with nonce'],
        ['shopifyOAuthCallback', 'HTTP GET', 'Handles OAuth redirect, exchanges code for access token'],
        ['shopifyImportProducts', 'HTTP POST', 'Imports products from Shopify, merges by SKU'],
        ['shopifyImportOrders', 'HTTP POST', 'Aggregates Shopify orders into monthly demandRecords'],
        ['shopifySyncInventory', 'HTTP POST', 'Pushes current stock levels to Shopify'],
        ['sendSupplierEmails', 'HTTP POST', 'Emails supplier with order link and portal access token'],
        ['sendManufacturerEmails', 'HTTP POST', 'Emails manufacturer with production order details'],
        ['sendFactoryEmails', 'HTTP POST', 'Emails raw material factory with procurement request'],
      ],
      [2800, 1800, 4760]
    ),
    caption('Table 4.5: Deployed Cloud Functions'),
    spacer(),
    body('Secrets are managed through Firebase Secret Manager. The functions use defineSecret() from the Firebase Functions v2 params module, which retrieves secret values at function invocation time rather than embedding them in the deployment package:'),
    spacer(),
    code('const SHOPIFY_API_KEY = defineSecret("SHOPIFY_API_KEY");'),
    code('const SHOPIFY_API_SECRET = defineSecret("SHOPIFY_API_SECRET");'),
    spacer(),
    body('SMTP credentials for email sending (SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS) are also managed as Firebase secrets. Environment variables accessible to functions include SHOPIFY_API_VERSION (defaulting to "2025-04") and CORS_ALLOWED_ORIGINS (defaulting to the production domain).'),
    pb()
  ];
}

module.exports = { chapter3, chapter4 };
