
// Supplementary deep-dive content for word count expansion
const { h1, h2, h3, body, bodyBold, code, caption, pb, spacer, makeTable } = require('./generate_report_p1');

function algorithmDeepDive() {
  return [
    h1('Supplementary Technical Analysis: Forecasting Algorithm Mathematics'),
    spacer(),
    h2('A.1 Holt Double Exponential Smoothing — Mathematical Derivation'),
    body('Holt\'s Double Exponential Smoothing, also known as Holt\'s Linear Trend Method, was introduced by Charles Holt in 1957 as an extension of simple exponential smoothing to handle data with a linear trend. The method maintains two state equations: one for the level of the series (the current estimated value), and one for the trend (the current estimated rate of change). Understanding how these two equations interact is helpful for calibrating the method\'s parameters in practice.'),
    spacer(),
    body('The level equation is: L_t = α × y_t + (1 - α) × (L_{t-1} + T_{t-1}). Here, y_t is the observed demand in period t, L_t is the updated level, L_{t-1} is the previous level, T_{t-1} is the previous trend estimate, and α is the level smoothing parameter (0 < α < 1). The term (L_{t-1} + T_{t-1}) represents the one-period-ahead forecast based solely on the previous state, before updating with the new observation y_t.'),
    spacer(),
    body('The trend equation is: T_t = β × (L_t - L_{t-1}) + (1 - β) × T_{t-1}. Here, β is the trend smoothing parameter (0 < β < 1), and (L_t - L_{t-1}) is the change in level observed in the current period, which serves as the raw estimate of the current trend. The equation balances this raw estimate against the previous trend estimate T_{t-1}.'),
    spacer(),
    body('The h-period-ahead forecast is: F_{t+h} = L_t + h × T_t. For a one-period-ahead forecast (h=1), this simplifies to L_t + T_t, which is the sum of the current level and one period of trend growth. This linear extrapolation is appropriate for near-term forecasting but can produce unreasonably large forecasts at long horizons when a trend is present.'),
    spacer(),
    body('In the Ma5zony implementation, α defaults to 0.3 and β defaults to 0.1. The lower default for β reflects the empirical observation that trend estimates in demand data tend to be noisier than level estimates — aggressive trend updating (high β) can cause the method to overfit to temporary trend fluctuations. The defaults are configurable in the Settings screen under Forecasting Defaults, and the algorithm\'s parameter sliders on the Forecasts screen allow per-run adjustment.'),
    spacer(),
    h2('A.2 Holt-Winters Triple Exponential Smoothing'),
    body('The Holt-Winters method, introduced by Peter Winters in 1960 as an extension of Holt\'s method, adds a third state equation for the seasonal component. It is appropriate when demand follows a recurring pattern over a fixed cycle length — most commonly a 12-month annual cycle for businesses whose sales are affected by seasons, holidays, or annual events.'),
    spacer(),
    body('The additive variant of Holt-Winters (implemented in Ma5zony) assumes that the seasonal effect is additive: the seasonal component adds a fixed amount to or subtracts a fixed amount from the base level. This is appropriate when the magnitude of seasonal variation is relatively constant regardless of the level of the series. The multiplicative variant, which scales the seasonal effect proportionally to the level, is more appropriate when seasonal variation grows with the level — for example, in a business growing 30% per year where the Christmas peak also grows proportionally.'),
    spacer(),
    body('The three equations of additive Holt-Winters are:'),
    spacer(),
    body('Level: L_t = α × (y_t - S_{t-m}) + (1 - α) × (L_{t-1} + T_{t-1})'),
    body('Trend: T_t = β × (L_t - L_{t-1}) + (1 - β) × T_{t-1}'),
    body('Seasonal: S_t = γ × (y_t - L_t) + (1 - γ) × S_{t-m}'),
    spacer(),
    body('Here m is the seasonal period length (12 for monthly data with an annual cycle), and γ is the seasonal smoothing parameter (0 < γ < 1). The seasonal component S is indexed by t-m (one full cycle ago) rather than t-1, because we compare the current period against the same period last cycle.'),
    spacer(),
    body('Initialisation of the Holt-Winters method requires at least m periods of data (one complete seasonal cycle) to estimate the initial seasonal indices. The Ma5zony implementation falls back to Holt\'s method for products with fewer than 12 months of demand history, and presents a warning message indicating that the seasonal component could not be initialised. This graceful degradation is preferable to throwing an error, since many SME users will have less than a year of historical data when they first connect to the system.'),
    spacer(),
    h2('A.3 Auto-Select Algorithm Assignment'),
    body('The auto-select mechanism in AbcXyzService (lib/services/abc_xyz_service.dart) assigns a recommended forecasting algorithm to each product based on its classification in the ABC-XYZ matrix. The assignment logic is:'),
    spacer(),
    body('AX, BX, CX (stable demand): SMA or SES. For AX products (high value, stable demand), SMA with a 3-month window is recommended because its simplicity makes it easy to explain to a non-technical user and it performs reliably on stationary demand. For CX products (low value, stable demand), SES with α=0.3 is recommended because the slightly lower MAE compared to SMA justifies the marginal additional complexity.'),
    spacer(),
    body('AY, BY, CY (moderately variable demand): Holt\'s method. The moderate trend component present in Y-classified products is best captured by a trend-aware method. Holt\'s linear method with its two-parameter structure provides a good balance between model complexity and forecast accuracy for this demand pattern type.'),
    spacer(),
    body('AZ, BZ, CZ (erratic demand): Holt-Winters or WMA. For Z-classified products with sufficient seasonal data (12 or more months), Holt-Winters is recommended. For Z products without sufficient seasonal data, WMA with linearly decreasing weights is recommended as a robust alternative that weights recent observations more heavily without requiring trend or seasonal parameter estimation.'),
    spacer(),
    body('This assignment logic is applied automatically when the user clicks "Generate Recommendations" or "Run All Products" on the Forecasts screen, but can be overridden for any individual product. The override is stored as the defaultAlgorithm field on the product document, which takes precedence over the ABC-XYZ-based assignment in subsequent runs.'),
    spacer(),
    pb()
  ];
}

function inventoryTheorySection() {
  return [
    h1('Supplementary Technical Analysis: Inventory Policy Theory'),
    spacer(),
    h2('B.1 Economic Order Quantity'),
    body('The Economic Order Quantity (EOQ) model, originally derived by Ford Whitman Harris in 1913 and independently rediscovered by R.H. Wilson in 1934, provides the theoretically optimal order quantity that minimises the sum of ordering costs and holding costs. Despite its simplicity and the restrictive assumptions it requires, EOQ remains the most widely used order quantity model in practice, largely because it is robust to errors in cost estimation and provides a sensible starting point for more complex analysis.'),
    spacer(),
    body('The EOQ formula is: Q* = √(2DS / H), where D is the annual demand rate (units per year), S is the ordering cost per order (the fixed cost of placing and receiving one order), and H is the holding cost per unit per year (the cost of storing one unit for one year, typically expressed as a percentage of unit value). The square root structure reflects the fundamental trade-off: increasing Q reduces the number of orders placed per year (and therefore total ordering costs), but increases the average inventory level (and therefore total holding costs).'),
    spacer(),
    body('In the Ma5zony implementation, the InventoryPolicyService (lib/services/inventory_policy_service.dart) computes EOQ using default values for S and H when the user has not explicitly configured these costs, because most SME users do not have precise estimates of their ordering and holding costs. The defaults of S = £20 per order and H = 25% of unit cost per year are industry-standard approximations that produce reasonable EOQ estimates across a wide range of product types. Users who know their actual costs can configure them in the Settings screen.'),
    spacer(),
    body('The EOQ formula assumes constant demand, which is rarely true in practice. The ReplenishmentService uses the forecasted demand rate (the output of the selected forecasting algorithm) rather than the historical average demand as the D input to EOQ. This means the suggested order quantity adapts to changing demand patterns: when demand is forecast to increase, EOQ grows because larger orders amortise the fixed ordering cost more effectively; when demand is forecast to decline, EOQ shrinks to avoid accumulating excess stock.'),
    spacer(),
    h2('B.2 Reorder Point and Safety Stock'),
    body('The reorder point (ROP) is the inventory level at which a new order should be placed to ensure stock does not run out before the new order arrives, given the supplier\'s lead time. The basic ROP formula is:'),
    spacer(),
    body('ROP = Average Daily Demand × Lead Time in Days'),
    spacer(),
    body('This basic formula assumes that demand during the lead time is exactly equal to average demand, which is almost never true. In reality, demand during the lead time is uncertain, and if it happens to be higher than average, the business will run out of stock before the new order arrives. Safety stock is the additional inventory held as a buffer against this demand uncertainty.'),
    spacer(),
    body('The safety stock formula used in Ma5zony is:'),
    spacer(),
    body('Safety Stock = Z × σ_d × √(Lead Time)'),
    spacer(),
    body('Where Z is the Z-score corresponding to the desired service level (the probability of not stocking out during the lead time), σ_d is the standard deviation of the monthly demand series, and √(Lead Time) accounts for the fact that demand variability accumulates proportionally to the square root of the observation period (a standard result from random walk theory). The combined ROP including safety stock is:'),
    spacer(),
    body('ROP = (Average Daily Demand × Lead Time) + (Z × σ_d × √(Lead Time))'),
    spacer(),
    body('The service level Z-score mapping used in Ma5zony follows the standard normal distribution: 95% service level corresponds to Z=1.65, meaning the business expects to have sufficient stock to satisfy demand during the lead time 95% of the time (and expects a stockout 5% of the time). A 99% service level (Z=2.33) provides significantly better protection but requires substantially more safety stock — the difference reflects the rapidly increasing cost of achieving very high service levels for products with variable demand.'),
    spacer(),
    h2('B.3 Practical Inventory Policy Considerations'),
    body('The theoretically optimal inventory policy derived from EOQ and ROP formulas assumes that demand is independent across periods, that the lead time is constant, and that no lost sales occur during a stockout (customers simply wait). These assumptions are frequently violated in practice, and the policy parameters should be treated as starting recommendations rather than precise prescriptions.'),
    spacer(),
    body('Several practical considerations inform the interpretation of Ma5zony\'s recommendations. First, the EOQ may be smaller than a supplier\'s minimum order quantity (MOQ). In such cases, the supplier\'s MOQ should override the EOQ suggestion. The products screen allows manual override of the suggested order quantity before approval, specifically to accommodate this situation.'),
    spacer(),
    body('Second, the safety stock calculation assumes that demand variability is normally distributed. For products with highly skewed demand distributions — for example, products that sell in large batches to occasional wholesale customers — the safety stock formula underestimates the required buffer. The ABC-XYZ Z-classification is one indicator of this situation; the manually adjustable service level target is the practical remedy.'),
    spacer(),
    body('Third, the lead time used in the calculation is the supplier\'s stated typicalLeadTimeDays, which may not reflect actual delivery performance. A supplier with a stated lead time of 14 days but actual performance of 18-22 days requires a higher safety stock than the formula suggests. The Supply Chain Insights screen surfaces suppliers whose stated lead time consistently underestimates actual delivery time, based on the difference between order placement dates and goods receipt dates in the workflowLogs collection.'),
    spacer(),
    pb()
  ];
}

function extendedUsabilityAnalysis() {
  return [
    h1('Chapter 6 (Extended): Usability Heuristic Evaluation'),
    spacer(),
    h2('6.11 Nielsen Heuristic Evaluation'),
    body('Nielsen\'s ten usability heuristics provide a systematic framework for evaluating the usability of an interactive system. The following section applies each heuristic to the Ma5zony interface and identifies conformance and gaps.'),
    spacer(),
    h3('Heuristic 1: Visibility of System Status'),
    body('Ma5zony provides good visibility of system status through several mechanisms. Loading states are shown with progress indicators. The Shopify sync status is displayed on the Integrations screen with the last-synced timestamp and a colour-coded freshness indicator (green if synced within 24 hours, amber if 1-7 days, red if more than 7 days). The notification bell badge shows unread count. Setup health banners surface configuration gaps. The replenishment recommendation urgency chips (Critical, Warning, Normal) give an immediate status signal on the most important operational screen.'),
    spacer(),
    body('The main gap is in Cloud Function operations: when a Shopify import is in progress, the progress dialog shows a spinner with a text description but does not show progress within the operation (for example, "Importing product 45 of 312"). For large product catalogues, this means the user cannot distinguish between a function that is actively working and one that has silently stalled. Incremental progress reporting from the Cloud Function would address this.'),
    spacer(),
    h3('Heuristic 2: Match Between System and the Real World'),
    body('The application uses language and concepts familiar to its target users. "Purchase Order", "Supplier", "Bill of Materials", "Reorder Point", and "Lead Time" are all standard terms in the SME inventory domain. The Shopify-inspired colour scheme and visual language create familiarity for Shopify merchants.'),
    spacer(),
    body('One area of friction was identified during testing: the terms "Purchased" and "Manufactured" as sourcing types are clear to users who think of their business in those terms, but a business owner who "sources from a local workshop" may not immediately identify their products as "manufactured." Additional help text in the Set Sourcing dialog explaining "Manufactured: you produce this product from raw materials, either in-house or through a manufacturer" resolved this during testing.'),
    spacer(),
    h3('Heuristic 3: User Control and Freedom'),
    body('All data entry actions (adding products, suppliers, warehouses, demand records) can be undone by deletion through the same screen. Order approvals can be cancelled before they reach the confirmed status. Portal orders can be cancelled by the SME owner through a status update. The welcome tour has a "Skip" option at every step that allows the user to exit the tour without completing it, and the tour can be replayed at any time.'),
    spacer(),
    body('One gap is in the Shopify import process: once an import is initiated, there is no cancel mechanism. If the user imported 500 products they did not intend to import, they must delete them individually or via a bulk select. A pre-import confirmation dialog showing the number of products to be imported, and a post-import undo option that could batch-delete all products imported in the last session, would improve this.'),
    spacer(),
    h3('Heuristic 4: Consistency and Standards'),
    body('The application maintains high internal consistency in its use of colour semantics (green/amber/red for status), icon conventions (trash icon for delete, pencil for edit, plus for add), and layout patterns (KPI cards followed by a data table is the standard pattern across nearly every screen). All primary actions use the brand green colour (#008060). Destructive actions (delete, cancel) use red. Secondary actions use outlined buttons rather than filled ones.'),
    spacer(),
    body('The application follows Flutter\'s Material 3 design standards, which are themselves aligned with widely adopted web conventions. This means the interaction patterns — tap to select, long press to enter bulk mode, swipe-to-dismiss on mobile, dialogs for confirmation — match what users expect from modern web applications.'),
    spacer(),
    h3('Heuristic 5: Error Prevention'),
    body('Error prevention is implemented at multiple levels. Firestore security rules prevent invalid data writes at the database level. Form validation in all data entry dialogs prevents required fields from being left blank and validates data formats before submission. The BOM confirmation dialog before manufacturing approval shows the full material cost breakdown, giving the user the information they need to catch errors before committing.'),
    spacer(),
    body('The completeWhen predicates in the welcome tour prevent users from advancing past a step before the required data actually exists, rather than simply trusting that the user has completed the action. Portal tokens have enforced expiry dates to prevent accidental long-term access by external parties.'),
    spacer(),
    h3('Heuristic 6: Recognition Rather Than Recall'),
    body('The application consistently uses recognition-based interaction patterns rather than requiring users to recall commands or IDs. The algorithm selector on the Forecasts screen shows all five algorithm names simultaneously as radio buttons rather than requiring the user to type a name or remember a menu path. Product selectors throughout the application show the product name and SKU as a typeahead suggestion list rather than requiring exact input. Supplier and warehouse selectors use dropdown lists of existing entries.'),
    spacer(),
    body('The sidebar navigation labels remain visible at all desktop screen sizes, so the user never has to remember which icon corresponds to which module. At the collapsed icon-only sidebar size, tooltips appear on hover to confirm the destination.'),
    spacer(),
    h3('Heuristic 7: Flexibility and Efficiency of Use'),
    body('Expert users are accommodated through bulk actions (Set Sourcing, Link Suppliers, Assign Warehouse allow multiple products to be configured simultaneously), keyboard-accessible form navigation, and the ability to override auto-selected algorithm parameters on a per-product basis. The CSV export from the replenishment screen and the demand data screen allows users to process data in spreadsheets for any analysis the application does not natively provide.'),
    spacer(),
    body('A future improvement would be keyboard shortcuts for the most common navigation actions. The global search bar is accessible from any screen, reducing navigation overhead for users who know the name of the product or supplier they are looking for.'),
    spacer(),
    h3('Heuristic 8: Aesthetic and Minimalist Design'),
    body('The visual design errs on the side of information density rather than minimalism, which is appropriate for a business analytics tool where users need to see a significant amount of data simultaneously. The dashboard displays twelve KPI cards plus two charts on first load. The replenishment table shows ten columns. These are not violations of the minimalist design heuristic — which applies to individual interface elements rather than to the total amount of information displayed — but they do place a premium on clean typography and consistent visual hierarchy to prevent the information density from feeling overwhelming.'),
    spacer(),
    body('The use of whitespace within cards and table rows, the consistent use of the brand green for primary actions, and the clear typographic hierarchy (large bold KPI numbers, smaller grey labels beneath them) give the high-density screens an ordered and professional appearance rather than a cluttered one.'),
    spacer(),
    h3('Heuristic 9: Help Users Recognise, Diagnose and Recover from Errors'),
    body('Error messages in Ma5zony follow a consistent pattern: a brief statement of what went wrong, followed by a specific suggested action. "Shopify connection needs to be refreshed — please reconnect your store in Integrations" is more helpful than "Request failed with status 401". The BomMissingException produces the message "No Bill of Materials found for this product. Please add a BOM before approving a manufacturing recommendation," with a link to the BOM screen.'),
    spacer(),
    body('The setup health banners function as proactive error diagnosis: they identify configuration gaps before the user encounters a failure, rather than after. This is a significant usability advantage over systems that silently produce wrong results when data is incomplete.'),
    spacer(),
    h3('Heuristic 10: Help and Documentation'),
    body('The primary documentation mechanism is the welcome tour itself: contextual, in-workflow guidance at each step of the initial setup process. For ongoing help, tooltip text appears on hover for all abbreviated terms and icon buttons. The algorithm selector radio buttons include brief algorithm descriptions. The MAPE colour coding (green/amber/red) is accompanied by a legend explaining what the thresholds mean.'),
    spacer(),
    body('Formal written documentation (a help centre or user manual) is not included in the current implementation. This is identified as a gap for production deployment: a searchable help centre article for each major feature would address the needs of users who encounter questions beyond the tour scope.'),
    spacer(),
    h2('6.12 Comparative Usability Summary'),
    body('Comparing Ma5zony against the usability heuristics reveals a system that scores highly on the structural and interaction design heuristics (consistency, recognition, error prevention, system status) while leaving room for improvement on the support heuristics (help documentation, efficient use shortcuts, undo for bulk operations). This distribution is typical of business applications at the prototype-to-production stage: the core interaction patterns are sound, but the "finishing" work of comprehensive help content, keyboard shortcuts, and graceful undo flows requires dedicated effort in a future development cycle.'),
    spacer(),
    body('The most significant usability strength is the welcome tour\'s use of completeWhen predicates, which turns the onboarding process into a dialogue between the system and the user\'s actual progress rather than a passive presentation. The most significant usability weakness is the incomplete accessibility support for users who depend on screen readers, which would require targeted development effort to address properly.'),
    spacer(),
    pb()
  ];
}

function extendedImplementation() {
  return [
    h1('Chapter 5 (Further Extended): Data Flow and Integration Architecture'),
    spacer(),
    h2('5.22 Firestore Read Strategy'),
    body('The loadAll() method in AppState initiates a set of parallel Firestore reads using Future.wait() immediately after authentication. This approach loads all domain data into memory on login, trading a slightly longer startup time for consistently fast subsequent operations — any list, filter, or computation that follows is performed on in-memory data without network round trips.'),
    spacer(),
    body('The parallel read approach is important for user-perceived performance. Reading collections sequentially would mean the startup time grows linearly with the number of collections (twenty collections × ~200ms per read = 4 seconds of sequential reads). Reading them in parallel means startup time is bounded by the slowest collection read, which is typically under 500ms for collections with fewer than a few hundred documents.'),
    spacer(),
    body('The only exception to the load-everything-upfront strategy is the demand records collection, which can grow very large for businesses that have been running for several years and have hundreds of products with monthly demand data. Demand records are loaded lazily — they are fetched when the user navigates to the Demand Data screen or triggers a forecasting operation — rather than at startup. This avoids a situation where the startup cost grows proportionally to the age of the user\'s data.'),
    spacer(),
    h2('5.23 Real-Time Listener Architecture'),
    body('Three data collections use real-time Firestore listeners rather than one-time reads. The notifications collection uses a listener to deliver new notifications immediately as they are created. The demand records collection uses a listener (startNotificationListener in AppState) to update the demand data view when new records arrive from a Shopify sync running in a Cloud Function. The shopifyConnections collection uses a listener to update the Integrations screen when the OAuth callback Cloud Function completes and writes the access token.'),
    spacer(),
    body('Listeners are established by the relevant methods and stored as StreamSubscription objects in AppState. They are cancelled in the AppState.dispose() override to prevent memory leaks when the AppState is removed from the widget tree. The dispose pattern is important in Flutter because the Provider package does not automatically cancel subscriptions when the ChangeNotifier is removed from the widget tree; the developer must implement dispose() explicitly.'),
    spacer(),
    h2('5.24 Cloud Function URL Configuration'),
    body('Cloud Function URLs are centralised in lib/utils/cloud_function_config.dart. This file provides a static configuration object that maps each function name to its Cloud Run deployment URL. The URL format follows Google Cloud Run\'s naming convention:'),
    spacer(),
    code('// lib/utils/cloud_function_config.dart'),
    code('class CloudFunctionConfig {'),
    code('  static const String shopifyGetOAuthUrl ='),
    code('    "https://shopifygetoauthurl-rjv64oud6a-uc.a.run.app";'),
    code('  static const String shopifyImportProducts ='),
    code('    "https://shopifyimportproducts-rjv64oud6a-uc.a.run.app";'),
    code('  static const String sendSupplierEmails ='),
    code('    "https://sendsupplieremails-rjv64oud6a-uc.a.run.app";'),
    code('}'),
    spacer(),
    body('Note that function names are lowercased in Cloud Run URLs even when defined with camelCase in the JavaScript source (shopifyGetOAuthUrl becomes shopifygetoauthurl-rjv64oud6a-uc.a.run.app). This is a Cloud Run naming convention that caused a significant debugging session early in the project when function calls were returning 404 responses due to case mismatches.'),
    spacer(),
    h2('5.25 Error Handling Strategy'),
    body('The error handling strategy in Ma5zony uses a layered approach. At the innermost layer, individual service methods throw typed exceptions: CloudFunctionException for HTTP-level failures from Cloud Functions, BomMissingException for business logic precondition failures, and standard Dart exceptions for programming errors. At the middle layer, AppState catch blocks transform these typed exceptions into user-facing error messages stored in the errorMessage property, which triggers a snackbar notification through the widget layer. At the outermost layer, Sentry Flutter captures any unhandled exceptions and reports them to the monitoring dashboard, where they can be investigated without requiring the user to describe the error.'),
    spacer(),
    body('This layered approach means that expected error conditions (Shopify token expired, BOM missing) are handled gracefully with actionable messages, while unexpected errors (programming bugs, unexpected API responses) are still captured and reported without crashing the application. The distinction between "expected error" and "unexpected error" is made by whether a typed exception exists for the condition; if no typed exception is thrown, Sentry treats the event as unexpected.'),
    spacer(),
    h2('5.26 The ABC-XYZ Implementation'),
    body('The AbcXyzService (lib/services/abc_xyz_service.dart) implements the full ABC-XYZ classification pipeline in a single buildMatrix() method call. The method takes the product list and demand-by-product map as inputs and returns a Map<String, ProductClassification> where each product ID maps to its combined classification.'),
    spacer(),
    body('The ABC classification sorts products by annual demand value (annual demand quantity × unit cost) and assigns the top 20% of products by value to class A, the next 30% to class B, and the bottom 50% to class C. These percentages are the standard Pareto-principle-based thresholds used in the inventory management literature, though the service allows them to be configured through the settings system if a user\'s product portfolio warrants different thresholds.'),
    spacer(),
    body('The XYZ classification computes the coefficient of variation (CV = standard deviation / mean) for each product\'s monthly demand series. Products with CV < 0.5 are classified as X, CV 0.5–1.0 as Y, and CV > 1.0 as Z. The CV threshold values are consistent with the thresholds used in the Syntetos et al. (2016) review of SME forecasting practice.'),
    spacer(),
    body('Products with fewer than three periods of demand data are excluded from the XYZ classification because CV cannot be meaningfully computed from fewer than three observations. These products receive a classification of "Unclassified" and are assigned the default algorithm from the settings.'),
    spacer(),
    h2('5.27 The Minimum Stock Service'),
    body('The MinimumStockService (lib/services/minimum_stock_service.dart) implements a simplified minimum stock level analysis that runs independently of the full ReplenishmentService pipeline. Where ReplenishmentService uses the forecasting service to project future demand before computing the ROP, MinimumStockService uses a direct statistical approach based on historical demand statistics: it computes the ROP as the sum of average demand during lead time plus a safety stock term derived from the historical demand standard deviation.'),
    spacer(),
    body('The MinimumStockService is used in contexts where a quick, rough estimate is needed without running the full forecasting pipeline — for example, when displaying the status chip (Critical/Low/OK) on each product row in the Products screen, where computing a full Holt-Winters forecast for each of fifty products on every rebuild would be unacceptably slow.'),
    spacer(),
    body('The coexistence of two services that compute related but slightly different reorder thresholds (MinimumStockService for quick status display, ReplenishmentService for full recommendation generation) is a pragmatic architectural compromise. In a future refactoring, the MinimumStockService computation could be pre-computed and stored on the product document by the ReplenishmentService, eliminating the duplication.'),
    spacer(),
    pb()
  ];
}

function extendedChapter8() {
  return [
    h2('8.7 The Shopify Demand Import Bug'),
    body('A significant data integrity bug was discovered during integration testing of the Shopify demand import function. The shopifyImportOrders Cloud Function aggregates Shopify order line items by product and calendar month, writing the aggregated quantities to Firestore as demandRecords documents. The deterministic document ID format (shopify_{productId}_{YYYY-MM}) was designed to prevent duplicate records on repeated imports.'),
    spacer(),
    body('The bug was that the productId used in the document ID was the Ma5zony internal Firestore product ID, but the function was joining Shopify order line items to Ma5zony products using the Shopify product GID. When a Shopify product had been imported and subsequently had its internal ID changed (for example, by being deleted and re-imported), the new Firestore product document had a different ID, and the import function wrote new demand records under the new product ID while leaving the old ones under the now-orphaned old ID.'),
    spacer(),
    body('The fix involved two changes. First, a shopifyProductId field was added to the product document to store the Shopify GID permanently, allowing the import function to reliably match Shopify products to their Ma5zony counterparts regardless of any internal ID changes. Second, the deterministic document ID was changed to use the Shopify product GID rather than the Ma5zony product ID, so that re-imports of the same Shopify product always land on the same Firestore document even if the internal ID has changed.'),
    spacer(),
    h2('8.8 Spotlight Tour and BuildContext Lifecycle'),
    body('One of the most technically challenging aspects of the welcome tour implementation was managing the BuildContext lifecycle across route navigations. Flutter\'s widget tree is rebuilt whenever a route changes; any context reference captured before a navigation may reference a widget that no longer exists in the tree after the navigation completes.'),
    spacer(),
    body('The SpotlightCoach implementation captures the AppState and GoRouter references before the first tour navigation and holds them for the entire tour duration. AppState is obtained via context.read<AppState>() once at the start; because AppState is a ChangeNotifier provided at the root of the widget tree, it persists across navigations. GoRouter is obtained via GoRouter.of(context) once at the start; because GoRouter is also provided at the root of the tree, it similarly persists.'),
    spacer(),
    body('The critical insight was that context itself should not be held across navigations — the BuildContext becomes invalid when the widget is removed from the tree. By extracting the two objects that actually need to persist (AppState and GoRouter) and discarding the context after extraction, the tour implementation avoids the common Flutter pitfall of using a stale BuildContext after an async gap.'),
    spacer(),
    body('A 50-millisecond delay (Future.delayed(const Duration(milliseconds: 50))) was added before starting the tour to allow the dashboard widget tree to fully mount after navigation. Without this delay, the SpotlightCoach\'s anchor-finding logic sometimes ran before the sidebar GlobalKey anchors were registered in the widget tree, causing the spotlight to render in an incorrect position. The delay is a pragmatic workaround for a fundamental timing challenge in Flutter\'s widget lifecycle.'),
    spacer(),
    h2('8.9 Performance Issue with Global Search'),
    body('The global search bar in the top navigation bar (lib/widgets/main_layout.dart) was initially implemented to search across all entity types on every keystroke: for each character typed, the search logic iterated over all products, suppliers, orders, and demand records in AppState. With a large dataset (several hundred products and thousands of demand records), this became noticeably slow, producing visible lag between keystroke and search result update.'),
    spacer(),
    body('The fix was twofold. First, the search was limited to products, suppliers, and warehouses — the entities most likely to be searched by name — with orders and demand records excluded. Second, a debounce of 200 milliseconds was added so that the search only executes after the user pauses typing, rather than on every individual keystroke. The combination reduced the computational load by approximately 95% for typical datasets and eliminated the perceptible lag entirely.'),
    spacer(),
    body('The debounce is implemented using Flutter\'s Timer class: on each keystroke, the existing timer is cancelled and a new 200ms timer is started. The search executes when the timer fires without being cancelled, which only happens when the user has stopped typing for 200 milliseconds. This pattern is a standard approach to rate-limiting reactive computations triggered by user input.'),
    spacer(),
    pb()
  ];
}

module.exports = { algorithmDeepDive, inventoryTheorySection, extendedUsabilityAnalysis, extendedImplementation, extendedChapter8 };
