
// Chapter 5: Implementation
const { h1, h2, h3, body, bodyBold, code, caption, pb, spacer, makeTable } = require('./generate_report_p1');

function chapter5() {
  return [
    h1('Chapter 5: Implementation'),
    spacer(),
    h2('5.1 Project Setup and Development Environment'),
    body('The project was initialised with flutter create and immediately configured for Firebase using the FlutterFire CLI, which generates the firebase_options.dart file containing platform-specific configuration for iOS, macOS, web, and Windows targets. All development was performed targeting the Chrome web browser, with flutter run -d chrome --web-port 53127 used consistently throughout the project to maintain the same port across browser sessions.'),
    spacer(),
    body('The Firebase project identifier is ma5zony, and the live production build is accessible at https://ma5zony.web.app. All deployment commands require the --project ma5zony flag to avoid accidentally deploying to an incorrect Firebase project. The key development commands are:'),
    spacer(),
    code('flutter pub get                              # Install Dart dependencies'),
    code('flutter run -d chrome --web-port 53127      # Launch dev server'),
    code('flutter build web --release                 # Production build'),
    code('flutter analyze                             # Static analysis'),
    code('flutter test                                # Run test suite'),
    code('cd functions && npm install                 # Install Cloud Function deps'),
    code('firebase deploy --project ma5zony           # Full production deploy'),
    code('firebase deploy --only functions --project ma5zony   # Functions only'),
    code('firebase deploy --only hosting --project ma5zony     # Hosting only'),
    code('firebase deploy --only firestore:rules --project ma5zony  # Rules only'),
    spacer(),
    body('The lib/ directory follows a feature-folder structure: each screen module lives under lib/features/<name>/, with separate directories for models (lib/models/), services (lib/services/), providers (lib/providers/), shared widgets (lib/widgets/), and utility constants (lib/utils/).'),
    spacer(),
    h2('5.2 Authentication and User Management'),
    body('Firebase Authentication handles all user identity operations. The FirebaseAuthService (lib/services/firebase_auth_service.dart) wraps the Firebase Auth SDK to provide email/password sign-in, registration, and sign-out. It also reads the user\'s profile document from Firestore to retrieve the role field that drives access control.'),
    spacer(),
    body('The application entry point in lib/main.dart initialises Firebase before rendering any UI:'),
    spacer(),
    code('void main() async {'),
    code('  WidgetsFlutterBinding.ensureInitialized();'),
    code('  await Firebase.initializeApp('),
    code('    options: DefaultFirebaseOptions.currentPlatform),'),
    code('  );'),
    code('  final appState = AppState()..loadAll();'),
    code('  runApp(MultiProvider('),
    code('    providers: [ChangeNotifierProvider.value(value: appState)],'),
    code('    child: Ma5zonyApp(appState: appState),'),
    code('  ));'),
    code('}'),
    spacer(),
    body('AppState listens to Firebase auth state changes through _authService.authStateChanges.listen(_onAuthStateChanged). When a user logs in, _onAuthStateChanged initialises all user-scoped services by calling _initRepo(firebaseUser.uid) and then invokes loadAll() to populate the in-memory domain state from Firestore.'),
    spacer(),
    body('Four roles are supported: SME Owner, Inventory Manager, Manufacturer, and Raw Material Factory. Roles are stored on the user\'s Firestore document and read at login. The lib/utils/role_guard.dart module provides the isOwner(AppUser?) helper function and the ownerOnlyRoutes list, which is used in the GoRouter redirect callback to prevent non-owner users from reaching financial screens.'),
    spacer(),
    body('Team members can be added by an SME Owner through the Settings screen. A team member\'s Firestore document stores an ownerId field pointing to the owner who invited them, which is used by the Firestore security rules to allow team members to read and write the owner\'s data subtree.'),
    spacer(),
    h2('5.3 Core Inventory Management'),
    h3('5.3.1 Products'),
    body('The Product model (lib/models/product.dart) is one of the most complex data models in the system, reflecting the variety of contexts in which products exist. Key fields include:'),
    spacer(),
    makeTable(
      ['Field', 'Type', 'Description'],
      [
        ['id', 'String', 'Firestore document ID'],
        ['sku', 'String', 'Stock-keeping unit identifier'],
        ['name', 'String', 'Display name'],
        ['category', 'String', 'Product category for classification'],
        ['unitCost', 'double', 'Unit purchase cost (purchased) or derived BOM cost (manufactured)'],
        ['currentStock', 'int', 'Current quantity in stock across all warehouses'],
        ['supplierId', 'String?', 'ID of primary supplier (purchased products)'],
        ['manufacturerId', 'String?', 'ID of manufacturer (manufactured products)'],
        ['warehouseId', 'String?', 'ID of primary warehouse'],
        ['sourcingType', 'String?', 'purchased or manufactured, drives replenishment path'],
        ['stockByWarehouse', 'Map<String,int>', 'Per-warehouse stock breakdown'],
        ['leadTimeDays', 'int', 'Procurement lead time in days'],
        ['shopifyProductId', 'String?', 'Shopify product GID for inventory sync'],
        ['shopifyInventoryItemId', 'String?', 'Shopify inventory item ID for stock updates'],
      ],
      [2400, 1600, 5360]
    ),
    caption('Table 5.1: Product model fields'),
    spacer(),
    body('Products are managed through the ProductsScreen (lib/features/products/products_screen.dart). The screen uses a PaginatedDataTable that supports search, category filtering, and column sorting. Bulk actions, Set Sourcing Type, Link Suppliers, Assign Warehouse, are available through a selection mode that allows multiple rows to be actioned simultaneously, reducing the time required to configure a newly imported product catalogue.'),
    spacer(),
    h3('5.3.2 Suppliers and Warehouses'),
    body('Suppliers are managed through the SuppliersScreen (lib/features/suppliers/suppliers_screen.dart). Each supplier record stores contact details, a typical lead time in days, and a performance rating. The lead time field is the most operationally significant: it feeds directly into the reorder point calculation in the replenishment engine.'),
    spacer(),
    body('Warehouses represent physical storage locations. Each warehouse stores its name, city, and country. Stock levels per warehouse are tracked at the product level through the stockByWarehouse map field on each product document, rather than at the warehouse level. This was a deliberate design decision made after an early implementation that maintained a totalStock counter on the warehouse document proved unreliable because the counter was not updated consistently across all code paths that modified product stock. The pivot to deriving warehouse stock from product-level data eliminated this inconsistency entirely, at the cost of a more complex read when computing warehouse-level aggregates.'),
    spacer(),
    h3('5.3.3 Demand Data'),
    body('Demand records are stored in the demandRecords subcollection under each user. Each record links a product (productId), a time period (periodStart as a monthly timestamp), and a quantity. The source field distinguishes manually entered records from those imported via the Shopify integration.'),
    spacer(),
    body('Shopify-imported demand records use deterministic document IDs in the format shopify_{productId}_{YYYY-MM}. This means that running the Shopify order import multiple times does not create duplicate records; it overwrites the existing record for each product-month combination with the latest aggregated value.'),
    spacer(),
    h2('5.4 The Demand Forecasting Engine'),
    body('The ForecastingService (lib/services/forecasting_service.dart) is a pure-Dart class that implements five forecasting algorithms independently of any UI or database concerns. This architectural decision makes the service trivially unit-testable and means the forecasting logic can be reused by multiple screens without any modification.'),
    spacer(),
    h3('5.4.1 Simple Moving Average'),
    body('The SMA implementation handles the case where the historical series is shorter than the configured window size by averaging all available data rather than returning zero. This is an important practical consideration for new users who have imported only one or two months of Shopify data:'),
    spacer(),
    code('double simpleMovingAverage(List<double> demand, int windowSize) {'),
    code('  if (demand.isEmpty || windowSize <= 0) return 0;'),
    code('  final effectiveWindow ='),
    code('    demand.length < windowSize ? demand.length : windowSize;'),
    code('  final window = demand.sublist(demand.length - effectiveWindow);'),
    code('  return window.reduce((a, b) => a + b) / effectiveWindow;'),
    code('}'),
    spacer(),
    h3('5.4.2 Single Exponential Smoothing'),
    body('SES applies the smoothing parameter α iteratively across the historical series. The initial forecast is set to the first demand value, which is the standard initialisation approach when a burn-in period is not available:'),
    spacer(),
    code('double singleExponentialSmoothing(List<double> demand, double alpha) {'),
    code('  if (demand.isEmpty) return 0;'),
    code('  double forecast = demand.first;'),
    code('  for (int i = 1; i < demand.length; i++) {'),
    code('    forecast = alpha * demand[i] + (1 - alpha) * forecast;'),
    code('  }'),
    code('  return forecast;'),
    code('}'),
    spacer(),
    h3('5.4.3 Holt-Winters Implementation'),
    body('The Holt-Winters method is the most computationally complex of the five algorithms implemented. It maintains three state components, level (L), trend (T), and seasonality (S), each updated through separate smoothing equations controlled by parameters α, β, and γ respectively. The seasonal component requires at least one complete seasonal cycle of data to initialise, which the implementation handles by falling back to a simpler method when insufficient data is available.'),
    spacer(),
    body('The auto-select mechanism in AbcXyzService recommends algorithms based on demand variability: Class X products (coefficient of variation below 0.5) are assigned SMA or SES; Class Y products (CV between 0.5 and 1.0) are assigned Holt; Class Z products (CV above 1.0) are assigned Holt-Winters or a weighted average that dampens the influence of erratic observations.'),
    spacer(),
    h3('5.4.4 Accuracy Metrics'),
    body('After running any forecast, the system computes three accuracy metrics across the historical period for which both actuals and fitted values are available:'),
    spacer(),
    body('Mean Absolute Error (MAE) is the average of the absolute differences between forecast and actual values. It is expressed in the same units as the demand quantity and is therefore immediately interpretable by a non-technical user.'),
    spacer(),
    body('Mean Absolute Percentage Error (MAPE) expresses the average error as a percentage of the actual demand value. This is useful for comparing forecast accuracy across products with different demand scales, but it is undefined when actual demand is zero, which the implementation handles by excluding zero-demand periods from the MAPE calculation.'),
    spacer(),
    body('Root Mean Squared Error (RMSE) gives proportionally more weight to larger errors. A forecast method with a lower RMSE than another but a higher MAPE is better at avoiding large misses even if its average error is slightly higher.'),
    spacer(),
    body('The results screen presents all three metrics as KPI cards with colour-coded thresholds: MAPE below 15% is shown in green, 15 to 30% in amber, and above 30% in red, giving the user an immediate visual indication of forecast quality.'),
    spacer(),
    h2('5.5 Replenishment System'),
    h3('5.5.1 Pipeline Architecture'),
    body('The ReplenishmentService (lib/services/replenishment_service.dart) orchestrates a multi-stage pipeline:'),
    spacer(),
    body('Stage 1, Demand Aggregation: Raw demand records for each product are passed to DemandAggregationService, which groups them by month, fills any gaps in the monthly series with zero values, and returns a clean time series suitable for the forecasting algorithms.'),
    spacer(),
    body('Stage 2, Forecast: The appropriate algorithm is run on the monthly series. If AbcXyzService has classified the product, the recommended algorithm for that class is used. Otherwise SMA with a three-month window is the default.'),
    spacer(),
    body('Stage 3, Inventory Policy: The forecast output feeds into InventoryPolicyService, which computes the reorder point, safety stock, and economic order quantity. The reorder point formula is:'),
    spacer(),
    body('ROP = (Average Daily Demand × Lead Time in Days) + Safety Stock'),
    spacer(),
    body('Safety stock is computed using the service-level Z-score approach: Safety Stock = Z × σ_demand × √(Lead Time), where σ_demand is the standard deviation of the monthly demand series and Z is the Z-score corresponding to the configured service level percentage (default 95%, Z = 1.65).'),
    spacer(),
    body('Stage 4, Recommendation Generation: For each product whose current stock is at or below its reorder point, a ReplenishmentRecommendation object is created. The recommendation includes the current stock, the reorder point, the suggested order quantity (defaulting to EOQ), the urgency classification (Critical, Warning, or Normal), and the estimated arrival date (today plus the supplier\'s lead time in days).'),
    spacer(),
    h3('5.5.2 Service Level Configuration'),
    body('The service level target is configurable per user in the Settings screen. The ReplenishmentService maps percentage targets to Z-scores through a lookup table:'),
    spacer(),
    code('static double serviceLevelToZ(double serviceLevelPercent) {'),
    code('  if (serviceLevelPercent >= 99) return 2.33;'),
    code('  if (serviceLevelPercent >= 97.5) return 1.96;'),
    code('  if (serviceLevelPercent >= 95) return 1.65;'),
    code('  if (serviceLevelPercent >= 90) return 1.28;'),
    code('  if (serviceLevelPercent >= 85) return 1.04;'),
    code('  if (serviceLevelPercent >= 80) return 0.84;'),
    code('  return 0.67;'),
    code('}'),
    spacer(),
    body('A higher service level target generates a higher safety stock recommendation, providing better protection against stockouts at the cost of higher inventory holding costs. The default of 95% is appropriate for most SME contexts and balances these competing concerns reasonably well.'),
    spacer(),
    h2('5.6 Manufacturing Workflow'),
    body('The manufacturing workflow handles the path from a low-stock manufactured product through to a production order with associated raw material procurement. The key distinction from the purchase path is that the cost of a manufactured product must be computed dynamically from the bill of materials rather than read from a static unit cost field.'),
    spacer(),
    h3('5.6.1 Bill of Materials'),
    body('A BOM document (stored in users/{uid}/boms/) links a finalProductId to a list of BomMaterial entries, each of which specifies a rawMaterialId and a quantityPerUnit. When a manufacturing approval is triggered, the system reads the relevant BOM and computes:'),
    spacer(),
    body('Estimated production cost = Σ (rawMaterial.unitCost × bomMaterial.quantityPerUnit × orderQuantity) + manufacturer.productionFeePerUnit × orderQuantity'),
    spacer(),
    body('The BOM confirmation dialog shown to the user before they approve a manufacturing recommendation displays this cost breakdown per material, the total estimated cost, and the manufacturer\'s contact details and production capacity.'),
    spacer(),
    body('A BomMissingException (defined in app_state.dart) is thrown when a manufacturing approval is attempted for a product without a BOM. This custom exception type allows the UI to display a specific, actionable error message, "Please add a Bill of Materials before approving a manufacturing recommendation", rather than a generic failure message.'),
    spacer(),
    h3('5.6.2 Production Order Lifecycle'),
    body('Production orders move through a defined status sequence: draft → materialsOrdered → materialsReady → inProduction → completed. Each status transition is recorded in the workflowLogs collection through the WorkflowService. The completed transition triggers an automatic stock increment in the product\'s currentStock field, representing the finished goods entering the warehouse.'),
    spacer(),
    body('When a production order is created, the system also generates factory orders (stored in the top-level factoryOrders collection) directed at each raw material supplier. Each factory order carries a unique, time-limited access token that is emailed to the supplier via the sendFactoryEmails Cloud Function. The supplier opens their factory portal URL to confirm their order.'),
    spacer(),
    h2('5.7 Shopify Integration'),
    h3('5.7.1 OAuth Flow'),
    body('The Shopify integration uses OAuth 2.0 with the Shopify Admin API. The flow begins when the user enters their shop\'s myshopify.com domain in the Integrations screen and clicks Connect. This triggers a call to the shopifyGetOAuthUrl Cloud Function, which generates a cryptographically random nonce, stores it in Firestore with a 10-minute expiry, and returns an authorisation URL:'),
    spacer(),
    code('const nonce = crypto.randomBytes(16).toString("hex");'),
    code('const expiresAt = new Date(Date.now() + 10 * 60 * 1000);'),
    code('await db.collection("users").doc(uid)'),
    code('  .collection("shopify").doc("pending_oauth")'),
    code('  .set({ nonce, shopDomain, createdAt: FieldValue.serverTimestamp(), expiresAt });'),
    code(''),
    code('const scopes = "read_products,read_inventory,read_orders";'),
    code('const authUrl = `https://${shopDomain}/admin/oauth/authorize` +'),
    code('  `?client_id=${SHOPIFY_API_KEY.value().trim()}` +'),
    code('  `&scope=${scopes}` +'),
    code('  `&redirect_uri=${encodeURIComponent(redirectUri)}` +'),
    code('  `&state=${uid}:${nonce}`;'),
    spacer(),
    body('After the merchant approves the connection in the Shopify admin, Shopify redirects to the shopifyOAuthCallback Cloud Function with an authorisation code, the shop domain, and the state parameter. The callback function verifies the HMAC signature on the redirect to confirm the request originated from Shopify:'),
    spacer(),
    code('const queryParams = { ...req.query };'),
    code('delete queryParams.hmac;'),
    code('const sorted = Object.keys(queryParams).sort()'),
    code('  .map(k => `${k}=${queryParams[k]}`).join("&");'),
    code('const digest = crypto.createHmac("sha256",'),
    code('  SHOPIFY_API_SECRET.value().trim()).update(sorted).digest("hex");'),
    code('if (!crypto.timingSafeEqual(Buffer.from(digest), Buffer.from(hmac))) {'),
    code('  res.status(401).send("Invalid HMAC"); return;'),
    code('}'),
    spacer(),
    body('After HMAC verification and nonce validation, the callback exchanges the authorisation code for a permanent access token using a server-to-server POST request to Shopify\'s token endpoint. The access token is stored in the user\'s shopifyConnections subcollection. It never touches the Flutter client; all subsequent Shopify API calls go through Cloud Functions that retrieve the token directly from Firestore using the Firebase Admin SDK.'),
    spacer(),
    h3('5.7.2 Product and Order Import'),
    body('The shopifyImportProducts function retrieves the merchant\'s product catalogue via the Shopify GraphQL Admin API and creates or updates product documents in Firestore, matching on SKU. Products that already exist in Firestore are updated rather than duplicated; new products from Shopify are created with a default sourcingType of null, which triggers the Set Sourcing step in the onboarding tour.'),
    spacer(),
    body('The shopifyImportOrders function retrieves fulfilled orders from Shopify\'s GraphQL API, aggregates the order line items by product and calendar month, and writes the results to the demandRecords subcollection. Because document IDs are deterministic (shopify_{productId}_{YYYY-MM}), re-running the import updates existing records rather than duplicating them.'),
    spacer(),
    h2('5.8 Real-Time Notifications'),
    body('In-app notifications are stored in the users/{uid}/notifications subcollection and delivered to the client through a Firestore real-time listener. The NotificationService (lib/services/notification_service.dart) establishes a Stream<List<AppNotification>> that the AppState class subscribes to and exposes as a reactive property.'),
    spacer(),
    body('Notifications are generated at several points in the workflow: when a purchase order is created, when a manufacturing order is approved, when a production order status changes, and when a Shopify sync completes or fails. The notification bell in the top bar shows an unread count badge that updates in real time as new notifications arrive.'),
    spacer(),
    h2('5.9 Progressive Web App Configuration'),
    body('The Flutter web build produces a Progressive Web App by default. The web/manifest.json defines the application name, icon set, theme colour, and display mode. The web/index.html contains the service worker registration and the splash screen configuration that shows the Ma5zony brand during initial load.'),
    spacer(),
    body('The PWA configuration allows users to install the application to their desktop or home screen from Chrome, Edge, or Safari. Once installed, the application behaves like a native application with its own window, taskbar icon, and offline splash screen. This is a significant usability benefit for users who access the application daily, as it removes the friction of navigating to a browser bookmark.'),
    pb()
  ];
}

module.exports = { chapter5 };
