// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError('Android is not configured — run flutterfire configure');
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not configured — run flutterfire configure');
      case TargetPlatform.fuchsia:
        throw UnsupportedError('Fuchsia is not supported');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuDIr8QoaXd7ElhxaegXj3JQZZl1XrhlY',
    appId: '1:184799104005:web:952337bffa1c112c2b606c',
    messagingSenderId: '184799104005',
    projectId: 'ma5zony',
    authDomain: 'ma5zony.firebaseapp.com',
    storageBucket: 'ma5zony.firebasestorage.app',
    measurementId: 'G-1B0D36MG3L',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD40i4yr6XSjuR8UvdrCDhVI4kQqKMDAyw',
    appId: '1:184799104005:ios:317368f927a512942b606c',
    messagingSenderId: '184799104005',
    projectId: 'ma5zony',
    storageBucket: 'ma5zony.firebasestorage.app',
    iosClientId: '184799104005-r6igftebke1r6iab4bi8u0nvht7m34pb.apps.googleusercontent.com',
    iosBundleId: 'com.ma5zony.ma5zony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD40i4yr6XSjuR8UvdrCDhVI4kQqKMDAyw',
    appId: '1:184799104005:ios:317368f927a512942b606c',
    messagingSenderId: '184799104005',
    projectId: 'ma5zony',
    storageBucket: 'ma5zony.firebasestorage.app',
    iosClientId: '184799104005-r6igftebke1r6iab4bi8u0nvht7m34pb.apps.googleusercontent.com',
    iosBundleId: 'com.ma5zony.ma5zony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuDIr8QoaXd7ElhxaegXj3JQZZl1XrhlY',
    appId: '1:184799104005:web:ee849a434f5e3aea2b606c',
    messagingSenderId: '184799104005',
    projectId: 'ma5zony',
    authDomain: 'ma5zony.firebaseapp.com',
    storageBucket: 'ma5zony.firebasestorage.app',
    measurementId: 'G-Z31EPYSLNY',
  );

}